# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.address_streets_by_city_request import AddressStreetsByCityRequest

class TestAddressStreetsByCityRequest(unittest.TestCase):
    """AddressStreetsByCityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressStreetsByCityRequest:
        """Test AddressStreetsByCityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddressStreetsByCityRequest`
        """
        model = AddressStreetsByCityRequest()
        if include_optional:
            return AddressStreetsByCityRequest(
                organization_id = '',
                city_id = '',
                include_deleted = False
            )
        else:
            return AddressStreetsByCityRequest(
                organization_id = '',
                city_id = '',
        )
        """

    def testAddressStreetsByCityRequest(self):
        """Test AddressStreetsByCityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
