# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.iiko_transport_public_api_contracts_organizations_organization_settings import IikoTransportPublicApiContractsOrganizationsOrganizationSettings

class TestIikoTransportPublicApiContractsOrganizationsOrganizationSettings(unittest.TestCase):
    """IikoTransportPublicApiContractsOrganizationsOrganizationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IikoTransportPublicApiContractsOrganizationsOrganizationSettings:
        """Test IikoTransportPublicApiContractsOrganizationsOrganizationSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IikoTransportPublicApiContractsOrganizationsOrganizationSettings`
        """
        model = IikoTransportPublicApiContractsOrganizationsOrganizationSettings()
        if include_optional:
            return IikoTransportPublicApiContractsOrganizationsOrganizationSettings(
                id = '',
                prices_vat_inclusive = True,
                loyalty_discount_affects_vat = True,
                version = '',
                address_format_type = 'Legacy',
                is_anonymous_guests_allowed = True,
                name = '',
                country = '',
                restaurant_address = '',
                latitude = 1.337,
                longitude = 1.337,
                use_uae_addressing_system = True,
                country_phone_code = '',
                marketing_source_required_in_delivery = True,
                default_delivery_city_id = '',
                delivery_city_ids = [
                    ''
                    ],
                delivery_service_type = 'CourierOnly',
                delivery_order_payment_settings = 'WhenOrderOnTheWay',
                default_call_center_payment_type_id = '',
                order_item_comment_enabled = True,
                is_confirmation_enabled = True,
                confirm_allowed_interval_in_minutes = 56,
                address_lookup = [
                    'DaData'
                    ],
                use_business_hours_and_mapping = True,
                currency_iso_name = '',
                external_data = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/common/external_data.iikoTransport.PublicApi.Contracts.Common.ExternalData(
                        key = '', 
                        value = '', )
                    ]
            )
        else:
            return IikoTransportPublicApiContractsOrganizationsOrganizationSettings(
                id = '',
        )
        """

    def testIikoTransportPublicApiContractsOrganizationsOrganizationSettings(self):
        """Test IikoTransportPublicApiContractsOrganizationsOrganizationSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
