# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.organization_get_programs_response import OrganizationGetProgramsResponse

class TestOrganizationGetProgramsResponse(unittest.TestCase):
    """OrganizationGetProgramsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationGetProgramsResponse:
        """Test OrganizationGetProgramsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationGetProgramsResponse`
        """
        model = OrganizationGetProgramsResponse()
        if include_optional:
            return OrganizationGetProgramsResponse(
                programs = [
                    iikocloud_client.models.organization/loyalty_program.Organization.LoyaltyProgram(
                        id = '', 
                        name = '', 
                        description = '', 
                        service_from = '2019-08-24 14:15:22.123', 
                        service_to = '2019-08-24 14:15:22.123', 
                        notify_about_balance_changes = True, 
                        program_type = null, 
                        is_active = True, 
                        wallet_id = '', 
                        marketing_campaigns = [
                            iikocloud_client.models.organization/marketing_campaign_info.Organization.MarketingCampaignInfo(
                                id = '', 
                                program_id = '', 
                                name = '', 
                                description = '', 
                                is_active = True, 
                                period_from = '2019-08-24 14:15:22.123', 
                                period_to = '2019-08-24 14:15:22.123', 
                                order_action_condition_bindings = [
                                    iikocloud_client.models.organization/marketing_campaign_action_condition_binding_info.Organization.MarketingCampaignActionConditionBindingInfo(
                                        id = '', 
                                        stop_further_execution = True, 
                                        actions = [
                                            iikocloud_client.models.organization/marketing_campaign_settings_info.Organization.MarketingCampaignSettingsInfo(
                                                id = '', 
                                                settings = '', 
                                                type_name = '', 
                                                check_sum = '', )
                                            ], 
                                        conditions = [
                                            iikocloud_client.models.organization/marketing_campaign_settings_info.Organization.MarketingCampaignSettingsInfo(
                                                id = '', 
                                                settings = '', 
                                                type_name = '', 
                                                check_sum = '', )
                                            ], )
                                    ], 
                                periodic_action_condition_bindings = [
                                    iikocloud_client.models.organization/marketing_campaign_action_condition_binding_info.Organization.MarketingCampaignActionConditionBindingInfo(
                                        id = '', 
                                        stop_further_execution = True, )
                                    ], 
                                overdraft_action_condition_bindings = [
                                    
                                    ], 
                                guest_registration_action_condition_bindings = [
                                    
                                    ], )
                            ], 
                        applied_organizations = [
                            ''
                            ], 
                        template_type = null, 
                        is_exchange_rate_enabled = True, 
                        refill_type = null, )
                    ]
            )
        else:
            return OrganizationGetProgramsResponse(
        )
        """

    def testOrganizationGetProgramsResponse(self):
        """Test OrganizationGetProgramsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
