# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.transport_reserves_add_order_payments_to_banquet_request import TransportReservesAddOrderPaymentsToBanquetRequest

class TestTransportReservesAddOrderPaymentsToBanquetRequest(unittest.TestCase):
    """TransportReservesAddOrderPaymentsToBanquetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransportReservesAddOrderPaymentsToBanquetRequest:
        """Test TransportReservesAddOrderPaymentsToBanquetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransportReservesAddOrderPaymentsToBanquetRequest`
        """
        model = TransportReservesAddOrderPaymentsToBanquetRequest()
        if include_optional:
            return TransportReservesAddOrderPaymentsToBanquetRequest(
                reserve_id = '',
                organization_id = '',
                payments = [
                    iikocloud_client.models.create_order_payment_schema.CreateOrderPaymentSchema(
                        payment_type_kind = '', 
                        sum = 0, 
                        payment_type_id = '', 
                        is_processed_externally = True, 
                        payment_additional_data = null, 
                        is_fiscalized_externally = True, 
                        is_prepay = True, )
                    ]
            )
        else:
            return TransportReservesAddOrderPaymentsToBanquetRequest(
                reserve_id = '',
                organization_id = '',
                payments = [
                    iikocloud_client.models.create_order_payment_schema.CreateOrderPaymentSchema(
                        payment_type_kind = '', 
                        sum = 0, 
                        payment_type_id = '', 
                        is_processed_externally = True, 
                        payment_additional_data = null, 
                        is_fiscalized_externally = True, 
                        is_prepay = True, )
                    ],
        )
        """

    def testTransportReservesAddOrderPaymentsToBanquetRequest(self):
        """Test TransportReservesAddOrderPaymentsToBanquetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
