# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.iiko_transport_public_api_contracts_web_hooks_get_web_hook_settings_response import IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse

class TestIikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse(unittest.TestCase):
    """IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse:
        """Test IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse`
        """
        model = IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse()
        if include_optional:
            return IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse(
                correlation_id = '',
                api_login_name = '',
                web_hooks_uri = '',
                auth_token = '',
                web_hooks_filter = iikocloud_client.models.iiko_transport/public_api/contracts/integration/web_hooks_filters/web_hooks_filter.iikoTransport.PublicApi.Contracts.Integration.WebHooksFilters.WebHooksFilter(
                    delivery_order_filter = null, 
                    table_order_filter = null, 
                    reserve_filter = null, 
                    stop_list_update_filter = null, 
                    personal_shift_filter = null, 
                    nomenclature_update_filter = null, 
                    business_hours_and_mapping_update_filter = null, )
            )
        else:
            return IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse(
                correlation_id = '',
                api_login_name = '',
                web_hooks_uri = '',
        )
        """

    def testIikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse(self):
        """Test IikoTransportPublicApiContractsWebHooksGetWebHookSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
