# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iiko_cloud_client.models.transport_reserves_restaurant_section import TransportReservesRestaurantSection

class TestTransportReservesRestaurantSection(unittest.TestCase):
    """TransportReservesRestaurantSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransportReservesRestaurantSection:
        """Test TransportReservesRestaurantSection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransportReservesRestaurantSection`
        """
        model = TransportReservesRestaurantSection()
        if include_optional:
            return TransportReservesRestaurantSection(
                id = '',
                terminal_group_id = '',
                name = '',
                tables = [
                    iiko_cloud_client.models.reserves_table_schema.ReservesTableSchema(
                        id = '', 
                        number = 56, 
                        name = '', 
                        seating_capacity = 56, 
                        revision = 56, 
                        is_deleted = True, 
                        pos_id = '', )
                    ],
                var_schema = iiko_cloud_client.models.reserves_section_schema_schema.ReservesSectionSchemaSchema(
                    width = 56, 
                    height = 56, 
                    mark_elements = [
                        iiko_cloud_client.models.reserves_restaurant_section_mark_schema.ReservesRestaurantSectionMarkSchema(
                            text = '', 
                            font = null, 
                            color = null, 
                            x = 56, 
                            y = 56, 
                            z = 56, 
                            angle = 1.337, 
                            width = 56, 
                            height = 56, )
                        ], 
                    table_elements = [
                        iiko_cloud_client.models.reserves_restaurant_section_table_schema.ReservesRestaurantSectionTableSchema(
                            table_id = '', 
                            x = 56, 
                            y = 56, 
                            z = 56, 
                            angle = 1.337, 
                            width = 56, 
                            height = 56, )
                        ], 
                    rectangle_elements = [
                        iiko_cloud_client.models.reserves_restaurant_section_rectangle_schema.ReservesRestaurantSectionRectangleSchema(
                            color = null, 
                            x = 56, 
                            y = 56, 
                            z = 56, 
                            angle = 1.337, 
                            width = 56, 
                            height = 56, )
                        ], 
                    ellipse_elements = [
                        iiko_cloud_client.models.reserves_restaurant_section_ellipse_schema.ReservesRestaurantSectionEllipseSchema(
                            color = null, 
                            x = 56, 
                            y = 56, 
                            z = 56, 
                            angle = 1.337, 
                            width = 56, 
                            height = 56, )
                        ], 
                    revision = 56, 
                    is_deleted = True, )
            )
        else:
            return TransportReservesRestaurantSection(
                id = '',
                terminal_group_id = '',
                name = '',
                tables = [
                    iiko_cloud_client.models.reserves_table_schema.ReservesTableSchema(
                        id = '', 
                        number = 56, 
                        name = '', 
                        seating_capacity = 56, 
                        revision = 56, 
                        is_deleted = True, 
                        pos_id = '', )
                    ],
        )
        """

    def testTransportReservesRestaurantSection(self):
        """Test TransportReservesRestaurantSection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
