# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.delivery_restrictions_delivery_geocode_service_type import DeliveryRestrictionsDeliveryGeocodeServiceType

class TestDeliveryRestrictionsDeliveryGeocodeServiceType(unittest.TestCase):
    """DeliveryRestrictionsDeliveryGeocodeServiceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeliveryRestrictionsDeliveryGeocodeServiceType(self):
        """Test DeliveryRestrictionsDeliveryGeocodeServiceType"""
        # inst = DeliveryRestrictionsDeliveryGeocodeServiceType()

if __name__ == '__main__':
    unittest.main()
