# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.api.employees_api import EmployeesApi


class TestEmployeesApi(unittest.IsolatedAsyncioTestCase):
    """EmployeesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EmployeesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_employees_couriers_active_location_by_terminal_post(self) -> None:
        """Test case for employees_couriers_active_location_by_terminal_post

        Returns list of all active (courier session is opened) courier's locations which are delivery drivers in specified   restaurant and are clocked in on specified delivery terminal.
        """
        pass

    async def test_employees_couriers_active_location_post(self) -> None:
        """Test case for employees_couriers_active_location_post

        Returns list of all active (courier session is opened) courier's locations which are delivery drivers   in specified restaurants.
        """
        pass

    async def test_employees_couriers_by_role_post(self) -> None:
        """Test case for employees_couriers_by_role_post

        Returns list of all employees which are delivery drivers in specified restaurants,   and checks whether each employee has passed role.
        """
        pass

    async def test_employees_couriers_locations_by_time_offset_post(self) -> None:
        """Test case for employees_couriers_locations_by_time_offset_post

        Method of obtaining drivers' coordinates history.
        """
        pass

    async def test_employees_couriers_post(self) -> None:
        """Test case for employees_couriers_post

        Returns list of all employees which are delivery drivers in specified restaurants.
        """
        pass

    async def test_employees_info_post(self) -> None:
        """Test case for employees_info_post

        Returns employee info.
        """
        pass

    async def test_employees_shift_clockin_post(self) -> None:
        """Test case for employees_shift_clockin_post

        Open personal session.
        """
        pass

    async def test_employees_shift_clockout_post(self) -> None:
        """Test case for employees_shift_clockout_post

        Close personal session.
        """
        pass

    async def test_employees_shift_is_open_post(self) -> None:
        """Test case for employees_shift_is_open_post

        Check if personal session is open.
        """
        pass

    async def test_employees_shifts_by_courier_post(self) -> None:
        """Test case for employees_shifts_by_courier_post

        Get terminal groups where employee session is opened.
        """
        pass


if __name__ == '__main__':
    unittest.main()
