# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.external_menu_v3 import ExternalMenuV3

class TestExternalMenuV3(unittest.TestCase):
    """ExternalMenuV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalMenuV3:
        """Test ExternalMenuV3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalMenuV3`
        """
        model = ExternalMenuV3()
        if include_optional:
            return ExternalMenuV3(
                tax_categories = [
                    iikocloud_client.models.tax_category_dto.TaxCategoryDto(
                        id = '', 
                        name = '', 
                        percentage = 1.337, )
                    ],
                product_categories = [
                    iikocloud_client.models.product_category_dto2.ProductCategoryDto2(
                        id = '', 
                        name = '', 
                        is_deleted = True, )
                    ],
                allergen_groups = [
                    iikocloud_client.models.allergen_group_dto.AllergenGroupDto(
                        id = '', 
                        code = '', 
                        name = '', 
                        is_deleted = null, )
                    ],
                customer_tag_groups = [
                    iikocloud_client.models.customer_tag_group2.CustomerTagGroup2(
                        id = '', 
                        name = '', 
                        select_several_tags = True, 
                        items = [
                            iikocloud_client.models.customer_tag_item2.CustomerTagItem2(
                                id = '', 
                                name = '', )
                            ], )
                    ],
                override_tax_categories = [
                    iikocloud_client.models.override_taxes_dto.OverrideTaxesDto(
                        order_type = '', 
                        base_tax_category = '', 
                        new_tax_category = '', )
                    ],
                revision = 56,
                format_version = 56,
                id = 56,
                name = '',
                description = '',
                button_image_url = '',
                intervals = [
                    iikocloud_client.models.interval_dto2.IntervalDto2(
                        organization_id = '00000000-0000-0000-0000-000000000000', 
                        from_time = '09:00', 
                        to_time = '23:00', )
                    ],
                combo_categories = [
                    iikocloud_client.models.combo_category_dto2.ComboCategoryDto2(
                        id = null, 
                        name = '', 
                        combos = [
                            iikocloud_client.models.combo_dto2.ComboDto2(
                                name = '', 
                                price = 0, 
                                groups = [
                                    iikocloud_client.models.combo_group_dto2.ComboGroupDto2(
                                        id = null, 
                                        name = '', 
                                        is_main_group = True, 
                                        items = [
                                            iikocloud_client.models.combo_group_item_dto2.ComboGroupItemDto2(
                                                item_id = '', 
                                                forbidden_modifiers = [
                                                    null
                                                    ], 
                                                size_id = '', 
                                                price_modification_amount = 1.337, 
                                                sizes = [
                                                    iikocloud_client.models.combo_group_item_size_dto2.ComboGroupItemSizeDto2(
                                                        combo_size_id = '', 
                                                        size_id = '', 
                                                        name = '', 
                                                        short_name = '', 
                                                        prices = [
                                                            iikocloud_client.models.external_menu_price_by_departments_dto6.ExternalMenuPriceByDepartmentsDto6(
                                                                organizations = [
                                                                    ''
                                                                    ], 
                                                                price = 0, 
                                                                tax_category_id = '', )
                                                            ], )
                                                    ], )
                                            ], 
                                        skip_step = True, )
                                    ], 
                                image = [
                                    null
                                    ], 
                                description = '', 
                                sizes = [
                                    iikocloud_client.models.combo_size_dto2.ComboSizeDto2(
                                        name = '', 
                                        id = '', 
                                        button_image = null, 
                                        short_name = '', )
                                    ], 
                                price_strategy = {"BY_COMPONENT", "FIXED", "CALCULATE"}, 
                                start_date = '{"2018-01-01T00:00:00+00:00"}', 
                                expiration_date = '{"2018-01-01T00:00:00+00:00"}', 
                                id = '', )
                            ], )
                    ],
                item_groups = [
                    iikocloud_client.models.external_menu_category2.ExternalMenuCategory2(
                        id = '00000000-0000-0000-0000-000000000000', 
                        name = '', 
                        description = '', 
                        button_image_url = 'https://102922.selcdn.ru/ecomm/someimage.png', 
                        iiko_group_id = '00000000-0000-0000-0000-000000000000', 
                        items = [
                            iikocloud_client.models.external_menu_item2.ExternalMenuItem2(
                                sku = '', 
                                name = '', 
                                description = '', 
                                item_sizes = [
                                    iikocloud_client.models.external_menu_item_size2.ExternalMenuItemSize2(
                                        sku = '', 
                                        size_code = '', 
                                        size_name = '', 
                                        is_default = True, 
                                        item_modifier_groups = [
                                            iikocloud_client.models.external_menu_modifier_group2.ExternalMenuModifierGroup2(
                                                name = '', 
                                                description = '', 
                                                restrictions = null, 
                                                is_hidden = True, 
                                                child_modifiers_have_min_max_restrictions = True, 
                                                sku = '', 
                                                splittable = null, 
                                                id = '00000000-0000-0000-0000-000000000000', )
                                            ], 
                                        prices = [
                                            iikocloud_client.models.external_menu_price_by_departments_dto2.ExternalMenuPriceByDepartmentsDto2(
                                                organizations = [
                                                    ''
                                                    ], 
                                                price = 0, 
                                                tax_category_id = '', )
                                            ], 
                                        nutritions = [
                                            iikocloud_client.models.nutrition_info_dto2.NutritionInfoDto2(
                                                fats = 1.337, 
                                                proteins = 1.337, 
                                                carbs = 1.337, 
                                                energy = 1.337, 
                                                saturated_fatty_acid = 1.337, 
                                                salt = 1.337, 
                                                sugar = 1.337, )
                                            ], 
                                        is_hidden = True, 
                                        measure_unit_type = 'GRAM', 
                                        button_image_url = 'https://102922.selcdn.ru/ecomm/someimage.png', 
                                        weight = 1.337, 
                                        id = '00000000-0000-0000-0000-000000000000', )
                                    ], 
                                modifier_schema_id = '00000000-0000-0000-0000-000000000000', 
                                modifier_schema_name = '', 
                                type = 'DISH', 
                                can_set_open_price = True, 
                                use_balance_for_sell = True, 
                                measure_unit = '', 
                                product_category_id = '00000000-0000-0000-0000-000000000000', 
                                customer_tag_groups = [
                                    iikocloud_client.models.selected_customer_tag2.SelectedCustomerTag2(
                                        customer_tag_group_id = '00000000-0000-0000-0000-000000000000', 
                                        selected_tag_ids = [
                                            null
                                            ], )
                                    ], 
                                payment_subject = '', 
                                payment_subject_code = '', 
                                outer_ean_code = '', 
                                is_marked = True, 
                                is_hidden = True, 
                                barcodes = [
                                    iikocloud_client.models.barcode_dto2.BarcodeDto2(
                                        barcode = '', 
                                        container = '', )
                                    ], 
                                order_item_type = 'Product', 
                                tax_category_id = '', 
                                allergen_group_ids = [
                                    null
                                    ], 
                                labels = [
                                    ''
                                    ], 
                                tags = [
                                    ''
                                    ], 
                                id = '00000000-0000-0000-0000-000000000000', 
                                splittable = null, )
                            ], 
                        schedule_id = '00000000-0000-0000-0000-000000000000', 
                        schedule_name = '', 
                        schedules = [
                            iikocloud_client.models.period_schedule_dto2.PeriodScheduleDto2(
                                begin = '09:00', 
                                end = '23:00', 
                                days_of_week = [
                                    'monday'
                                    ], )
                            ], 
                        is_hidden = True, 
                        labels = [
                            ''
                            ], 
                        tags = [
                            ''
                            ], )
                    ]
            )
        else:
            return ExternalMenuV3(
                id = 56,
                combo_categories = [
                    iikocloud_client.models.combo_category_dto2.ComboCategoryDto2(
                        id = null, 
                        name = '', 
                        combos = [
                            iikocloud_client.models.combo_dto2.ComboDto2(
                                name = '', 
                                price = 0, 
                                groups = [
                                    iikocloud_client.models.combo_group_dto2.ComboGroupDto2(
                                        id = null, 
                                        name = '', 
                                        is_main_group = True, 
                                        items = [
                                            iikocloud_client.models.combo_group_item_dto2.ComboGroupItemDto2(
                                                item_id = '', 
                                                forbidden_modifiers = [
                                                    null
                                                    ], 
                                                size_id = '', 
                                                price_modification_amount = 1.337, 
                                                sizes = [
                                                    iikocloud_client.models.combo_group_item_size_dto2.ComboGroupItemSizeDto2(
                                                        combo_size_id = '', 
                                                        size_id = '', 
                                                        name = '', 
                                                        short_name = '', 
                                                        prices = [
                                                            iikocloud_client.models.external_menu_price_by_departments_dto6.ExternalMenuPriceByDepartmentsDto6(
                                                                organizations = [
                                                                    ''
                                                                    ], 
                                                                price = 0, 
                                                                tax_category_id = '', )
                                                            ], )
                                                    ], )
                                            ], 
                                        skip_step = True, )
                                    ], 
                                image = [
                                    null
                                    ], 
                                description = '', 
                                sizes = [
                                    iikocloud_client.models.combo_size_dto2.ComboSizeDto2(
                                        name = '', 
                                        id = '', 
                                        button_image = null, 
                                        short_name = '', )
                                    ], 
                                price_strategy = {"BY_COMPONENT", "FIXED", "CALCULATE"}, 
                                start_date = '{"2018-01-01T00:00:00+00:00"}', 
                                expiration_date = '{"2018-01-01T00:00:00+00:00"}', 
                                id = '', )
                            ], )
                    ],
                item_groups = [
                    iikocloud_client.models.external_menu_category2.ExternalMenuCategory2(
                        id = '00000000-0000-0000-0000-000000000000', 
                        name = '', 
                        description = '', 
                        button_image_url = 'https://102922.selcdn.ru/ecomm/someimage.png', 
                        iiko_group_id = '00000000-0000-0000-0000-000000000000', 
                        items = [
                            iikocloud_client.models.external_menu_item2.ExternalMenuItem2(
                                sku = '', 
                                name = '', 
                                description = '', 
                                item_sizes = [
                                    iikocloud_client.models.external_menu_item_size2.ExternalMenuItemSize2(
                                        sku = '', 
                                        size_code = '', 
                                        size_name = '', 
                                        is_default = True, 
                                        item_modifier_groups = [
                                            iikocloud_client.models.external_menu_modifier_group2.ExternalMenuModifierGroup2(
                                                name = '', 
                                                description = '', 
                                                restrictions = null, 
                                                is_hidden = True, 
                                                child_modifiers_have_min_max_restrictions = True, 
                                                sku = '', 
                                                splittable = null, 
                                                id = '00000000-0000-0000-0000-000000000000', )
                                            ], 
                                        prices = [
                                            iikocloud_client.models.external_menu_price_by_departments_dto2.ExternalMenuPriceByDepartmentsDto2(
                                                organizations = [
                                                    ''
                                                    ], 
                                                price = 0, 
                                                tax_category_id = '', )
                                            ], 
                                        nutritions = [
                                            iikocloud_client.models.nutrition_info_dto2.NutritionInfoDto2(
                                                fats = 1.337, 
                                                proteins = 1.337, 
                                                carbs = 1.337, 
                                                energy = 1.337, 
                                                saturated_fatty_acid = 1.337, 
                                                salt = 1.337, 
                                                sugar = 1.337, )
                                            ], 
                                        is_hidden = True, 
                                        measure_unit_type = 'GRAM', 
                                        button_image_url = 'https://102922.selcdn.ru/ecomm/someimage.png', 
                                        weight = 1.337, 
                                        id = '00000000-0000-0000-0000-000000000000', )
                                    ], 
                                modifier_schema_id = '00000000-0000-0000-0000-000000000000', 
                                modifier_schema_name = '', 
                                type = 'DISH', 
                                can_set_open_price = True, 
                                use_balance_for_sell = True, 
                                measure_unit = '', 
                                product_category_id = '00000000-0000-0000-0000-000000000000', 
                                customer_tag_groups = [
                                    iikocloud_client.models.selected_customer_tag2.SelectedCustomerTag2(
                                        customer_tag_group_id = '00000000-0000-0000-0000-000000000000', 
                                        selected_tag_ids = [
                                            null
                                            ], )
                                    ], 
                                payment_subject = '', 
                                payment_subject_code = '', 
                                outer_ean_code = '', 
                                is_marked = True, 
                                is_hidden = True, 
                                barcodes = [
                                    iikocloud_client.models.barcode_dto2.BarcodeDto2(
                                        barcode = '', 
                                        container = '', )
                                    ], 
                                order_item_type = 'Product', 
                                tax_category_id = '', 
                                allergen_group_ids = [
                                    null
                                    ], 
                                labels = [
                                    ''
                                    ], 
                                tags = [
                                    ''
                                    ], 
                                id = '00000000-0000-0000-0000-000000000000', 
                                splittable = null, )
                            ], 
                        schedule_id = '00000000-0000-0000-0000-000000000000', 
                        schedule_name = '', 
                        schedules = [
                            iikocloud_client.models.period_schedule_dto2.PeriodScheduleDto2(
                                begin = '09:00', 
                                end = '23:00', 
                                days_of_week = [
                                    'monday'
                                    ], )
                            ], 
                        is_hidden = True, 
                        labels = [
                            ''
                            ], 
                        tags = [
                            ''
                            ], )
                    ],
        )
        """

    def testExternalMenuV3(self):
        """Test ExternalMenuV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
