# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.combo_group_item_dto4 import ComboGroupItemDto4

class TestComboGroupItemDto4(unittest.TestCase):
    """ComboGroupItemDto4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComboGroupItemDto4:
        """Test ComboGroupItemDto4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComboGroupItemDto4`
        """
        model = ComboGroupItemDto4()
        if include_optional:
            return ComboGroupItemDto4(
                item_id = '',
                forbidden_modifiers = [
                    null
                    ],
                size_id = '',
                price_modification_amount = 1.337,
                sizes = [
                    iikocloud_client.models.combo_group_item_size_dto4.ComboGroupItemSizeDto4(
                        combo_size_id = '', 
                        size_id = '', 
                        name = '', 
                        short_name = '', 
                        prices = [
                            iikocloud_client.models.external_menu_price_by_departments_dto8.ExternalMenuPriceByDepartmentsDto8(
                                organizations = [
                                    ''
                                    ], 
                                price = 0, 
                                tax_category_id = '', )
                            ], )
                    ]
            )
        else:
            return ComboGroupItemDto4(
                item_id = '',
        )
        """

    def testComboGroupItemDto4(self):
        """Test ComboGroupItemDto4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
