# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iiko_cloud_client.api.discounts_and_promotions_api import DiscountsAndPromotionsApi


class TestDiscountsAndPromotionsApi(unittest.IsolatedAsyncioTestCase):
    """DiscountsAndPromotionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DiscountsAndPromotionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api1_loyalty_iiko_calculate_post(self) -> None:
        """Test case for api1_loyalty_iiko_calculate_post

        Calculate checkin.
        """
        pass

    async def test_api1_loyalty_iiko_coupons_by_series_post(self) -> None:
        """Test case for api1_loyalty_iiko_coupons_by_series_post

        Get non-activated coupons
        """
        pass

    async def test_api1_loyalty_iiko_coupons_info_post(self) -> None:
        """Test case for api1_loyalty_iiko_coupons_info_post

        Get coupon info.
        """
        pass

    async def test_api1_loyalty_iiko_coupons_series_post(self) -> None:
        """Test case for api1_loyalty_iiko_coupons_series_post

        Get coupon series with non-activated coupons.
        """
        pass

    async def test_api1_loyalty_iiko_manual_condition_post(self) -> None:
        """Test case for api1_loyalty_iiko_manual_condition_post

        Get manual conditions.
        """
        pass

    async def test_api1_loyalty_iiko_program_post(self) -> None:
        """Test case for api1_loyalty_iiko_program_post

        Get programs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
