# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from iikocloud_client.models.combo_dto3_image_inner import ComboDto3ImageInner
from iikocloud_client.models.combo_group_dto3 import ComboGroupDto3
from iikocloud_client.models.combo_size_dto3 import ComboSizeDto3
from typing import Optional, Set
from typing_extensions import Self

class ComboDto3(BaseModel):
    """
    ComboDto3
    """ # noqa: E501
    name: StrictStr = Field(description="Combo name")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Combo price, if price strategy is fixed")
    groups: Optional[List[ComboGroupDto3]] = None
    image: List[Optional[ComboDto3ImageInner]] = Field(description="Combo image")
    description: Optional[StrictStr] = Field(default='', description="Combo description")
    sizes: Optional[List[ComboSizeDto3]] = Field(default=None, description="Available sizes for combo (can be empty)")
    price_strategy: StrictStr = Field(alias="priceStrategy")
    start_date: StrictStr = Field(description="The date when the combo will be available until", alias="startDate")
    expiration_date: StrictStr = Field(description="The date when the combo will be available until", alias="expirationDate")
    id: UUID = Field(description="Combo id")
    __properties: ClassVar[List[str]] = ["name", "price", "groups", "image", "description", "sizes", "priceStrategy", "startDate", "expirationDate", "id"]

    @field_validator('price_strategy')
    def price_strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BY_COMPONENT', 'FIXED', 'CALCULATE']):
            raise ValueError("must be one of enum values ('BY_COMPONENT', 'FIXED', 'CALCULATE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComboDto3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in image (list)
        _items = []
        if self.image:
            for _item_image in self.image:
                if _item_image:
                    _items.append(_item_image.to_dict())
            _dict['image'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sizes (list)
        _items = []
        if self.sizes:
            for _item_sizes in self.sizes:
                if _item_sizes:
                    _items.append(_item_sizes.to_dict())
            _dict['sizes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComboDto3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "price": obj.get("price"),
            "groups": [ComboGroupDto3.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "image": [ComboDto3ImageInner.from_dict(_item) for _item in obj["image"]] if obj.get("image") is not None else None,
            "description": obj.get("description") if obj.get("description") is not None else '',
            "sizes": [ComboSizeDto3.from_dict(_item) for _item in obj["sizes"]] if obj.get("sizes") is not None else None,
            "priceStrategy": obj.get("priceStrategy"),
            "startDate": obj.get("startDate"),
            "expirationDate": obj.get("expirationDate"),
            "id": obj.get("id")
        })
        return _obj


