# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from iikocloud_client.models.deliveries_common_coordinates import DeliveriesCommonCoordinates
from iikocloud_client.models.deliveries_request_create_order_address import DeliveriesRequestCreateOrderAddress
from typing import Optional, Set
from typing_extensions import Self

class DeliveriesRequestCreateOrderDeliveryPoint(BaseModel):
    """
    Delivery location details.
    """ # noqa: E501
    coordinates: Optional[DeliveriesCommonCoordinates] = Field(default=None, description="Delivery address coordinates.  > Allowed from version `7.7.3`.")
    address: Optional[DeliveriesRequestCreateOrderAddress] = Field(default=None, description="Order delivery address.                > The use of type **City** is allowed if the parameter **addressFormatType == City**.                > Can be obtained by `/api/1/organizations` or `/api/1/organizations/settings` operations (`addressFormatType` parameter).")
    external_cartography_id: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=100)]] = Field(default=None, description="Delivery location custom code in customer's API system.", alias="externalCartographyId")
    comment: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=500)]] = Field(default=None, description="Additional information.")
    __properties: ClassVar[List[str]] = ["coordinates", "address", "externalCartographyId", "comment"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliveriesRequestCreateOrderDeliveryPoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coordinates
        if self.coordinates:
            _dict['coordinates'] = self.coordinates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # set to None if coordinates (nullable) is None
        # and model_fields_set contains the field
        if self.coordinates is None and "coordinates" in self.model_fields_set:
            _dict['coordinates'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if external_cartography_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_cartography_id is None and "external_cartography_id" in self.model_fields_set:
            _dict['externalCartographyId'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliveriesRequestCreateOrderDeliveryPoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coordinates": DeliveriesCommonCoordinates.from_dict(obj["coordinates"]) if obj.get("coordinates") is not None else None,
            "address": DeliveriesRequestCreateOrderAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "externalCartographyId": obj.get("externalCartographyId"),
            "comment": obj.get("comment")
        })
        return _obj


