# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from iikocloud_client.models.deliveries_request_create_order_dynamic_discount import DeliveriesRequestCreateOrderDynamicDiscount
from typing import Optional, Set
from typing_extensions import Self

class DeliveriesRequestCreateOrderLoyaltyInfo(BaseModel):
    """
    Information about Loyalty app.
    """ # noqa: E501
    coupon: Optional[StrictStr] = Field(default=None, description="Coupon No. that was considered when calculating loyalty program.")
    applicable_manual_conditions: Optional[List[UUID]] = Field(default=None, description="Information about applied manual conditions.", alias="applicableManualConditions")
    dynamic_discounts: Optional[List[DeliveriesRequestCreateOrderDynamicDiscount]] = Field(default=None, description="Dynamic discounts.   > Allowed from version `9.4.6`.", alias="dynamicDiscounts")
    __properties: ClassVar[List[str]] = ["coupon", "applicableManualConditions", "dynamicDiscounts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliveriesRequestCreateOrderLoyaltyInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dynamic_discounts (list)
        _items = []
        if self.dynamic_discounts:
            for _item_dynamic_discounts in self.dynamic_discounts:
                if _item_dynamic_discounts:
                    _items.append(_item_dynamic_discounts.to_dict())
            _dict['dynamicDiscounts'] = _items
        # set to None if coupon (nullable) is None
        # and model_fields_set contains the field
        if self.coupon is None and "coupon" in self.model_fields_set:
            _dict['coupon'] = None

        # set to None if applicable_manual_conditions (nullable) is None
        # and model_fields_set contains the field
        if self.applicable_manual_conditions is None and "applicable_manual_conditions" in self.model_fields_set:
            _dict['applicableManualConditions'] = None

        # set to None if dynamic_discounts (nullable) is None
        # and model_fields_set contains the field
        if self.dynamic_discounts is None and "dynamic_discounts" in self.model_fields_set:
            _dict['dynamicDiscounts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliveriesRequestCreateOrderLoyaltyInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coupon": obj.get("coupon"),
            "applicableManualConditions": obj.get("applicableManualConditions"),
            "dynamicDiscounts": [DeliveriesRequestCreateOrderDynamicDiscount.from_dict(_item) for _item in obj["dynamicDiscounts"]] if obj.get("dynamicDiscounts") is not None else None
        })
        return _obj


