# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iikocloud_client.models.external_menu_item import ExternalMenuItem
from iikocloud_client.models.label_dto import LabelDto
from iikocloud_client.models.period_schedule_dto import PeriodScheduleDto
from iikocloud_client.models.tag_dto import TagDto
from typing import Optional, Set
from typing_extensions import Self

class ExternalMenuCategory(BaseModel):
    """
    ExternalMenuCategory
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Category ID")
    name: Optional[StrictStr] = Field(default='', description="Category name")
    description: Optional[StrictStr] = Field(default='', description="Category description")
    button_image_url: Optional[StrictStr] = Field(default=None, description="Link to image", alias="buttonImageUrl")
    header_image_url: Optional[StrictStr] = Field(default=None, alias="headerImageUrl")
    iiko_group_id: Optional[StrictStr] = Field(default=None, description="iikoGroupId", alias="iikoGroupId")
    items: List[ExternalMenuItem]
    schedule_id: Optional[StrictStr] = Field(default=None, description="Category schedule GUID", alias="scheduleId")
    schedule_name: Optional[StrictStr] = Field(default=None, description="Category schedule name", alias="scheduleName")
    schedules: Optional[List[PeriodScheduleDto]] = Field(default=None, description="Category schedule intervals")
    is_hidden: Optional[StrictBool] = Field(default=False, description="Visibility flag", alias="isHidden")
    tags: Optional[List[TagDto]] = None
    labels: Optional[List[LabelDto]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "buttonImageUrl", "headerImageUrl", "iikoGroupId", "items", "scheduleId", "scheduleName", "schedules", "isHidden", "tags", "labels"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalMenuCategory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in schedules (list)
        _items = []
        if self.schedules:
            for _item_schedules in self.schedules:
                if _item_schedules:
                    _items.append(_item_schedules.to_dict())
            _dict['schedules'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if button_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.button_image_url is None and "button_image_url" in self.model_fields_set:
            _dict['buttonImageUrl'] = None

        # set to None if header_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.header_image_url is None and "header_image_url" in self.model_fields_set:
            _dict['headerImageUrl'] = None

        # set to None if iiko_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.iiko_group_id is None and "iiko_group_id" in self.model_fields_set:
            _dict['iikoGroupId'] = None

        # set to None if schedule_id (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_id is None and "schedule_id" in self.model_fields_set:
            _dict['scheduleId'] = None

        # set to None if schedule_name (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_name is None and "schedule_name" in self.model_fields_set:
            _dict['scheduleName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalMenuCategory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name") if obj.get("name") is not None else '',
            "description": obj.get("description") if obj.get("description") is not None else '',
            "buttonImageUrl": obj.get("buttonImageUrl"),
            "headerImageUrl": obj.get("headerImageUrl"),
            "iikoGroupId": obj.get("iikoGroupId"),
            "items": [ExternalMenuItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "scheduleId": obj.get("scheduleId"),
            "scheduleName": obj.get("scheduleName"),
            "schedules": [PeriodScheduleDto.from_dict(_item) for _item in obj["schedules"]] if obj.get("schedules") is not None else None,
            "isHidden": obj.get("isHidden") if obj.get("isHidden") is not None else False,
            "tags": [TagDto.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "labels": [LabelDto.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None
        })
        return _obj


