# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from iikocloud_client.models.iiko_transport_public_api_contracts_deliveries_common_gender import IikoTransportPublicApiContractsDeliveriesCommonGender
from iikocloud_client.models.iiko_transport_public_api_contracts_deliveries_request_create_order_customer import IikoTransportPublicApiContractsDeliveriesRequestCreateOrderCustomer
from typing import Optional, Set
from typing_extensions import Self

class IikoTransportPublicApiContractsDeliveriesRequestCreateOrderRegularCustomer(IikoTransportPublicApiContractsDeliveriesRequestCreateOrderCustomer):
    """
    IikoTransportPublicApiContractsDeliveriesRequestCreateOrderRegularCustomer
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Existing customer ID in RMS.   > If null - the phone number is searched in database, otherwise the new customer is created in RMS.")
    name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=60)]] = Field(default=None, description="Name of customer.  > Required for new customers (i.e. if \"id\" == null)  > Not required if \"id\" specified.")
    surname: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=60)]] = Field(default=None, description="Last name.")
    comment: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=60)]] = Field(default=None, description="Comment.")
    birthdate: Optional[StrictStr] = Field(default=None, description="Date of birth.")
    email: Optional[StrictStr] = Field(default=None, description="Email.")
    should_receive_promo_actions_info: Optional[StrictBool] = Field(default=None, description="Deprecated, use \"shouldReceiveOrderStatusNotifications\" instead.", alias="shouldReceivePromoActionsInfo")
    should_receive_order_status_notifications: Optional[StrictBool] = Field(default=None, description="Whether customer receives order status notification messages.", alias="shouldReceiveOrderStatusNotifications")
    gender: Optional[IikoTransportPublicApiContractsDeliveriesCommonGender] = Field(default=None, description="Gender.")
    __properties: ClassVar[List[str]] = ["type", "id", "name", "surname", "comment", "birthdate", "email", "shouldReceivePromoActionsInfo", "shouldReceiveOrderStatusNotifications", "gender"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IikoTransportPublicApiContractsDeliveriesRequestCreateOrderRegularCustomer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if surname (nullable) is None
        # and model_fields_set contains the field
        if self.surname is None and "surname" in self.model_fields_set:
            _dict['surname'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        # set to None if birthdate (nullable) is None
        # and model_fields_set contains the field
        if self.birthdate is None and "birthdate" in self.model_fields_set:
            _dict['birthdate'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if should_receive_promo_actions_info (nullable) is None
        # and model_fields_set contains the field
        if self.should_receive_promo_actions_info is None and "should_receive_promo_actions_info" in self.model_fields_set:
            _dict['shouldReceivePromoActionsInfo'] = None

        # set to None if should_receive_order_status_notifications (nullable) is None
        # and model_fields_set contains the field
        if self.should_receive_order_status_notifications is None and "should_receive_order_status_notifications" in self.model_fields_set:
            _dict['shouldReceiveOrderStatusNotifications'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IikoTransportPublicApiContractsDeliveriesRequestCreateOrderRegularCustomer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "surname": obj.get("surname"),
            "comment": obj.get("comment"),
            "birthdate": obj.get("birthdate"),
            "email": obj.get("email"),
            "shouldReceivePromoActionsInfo": obj.get("shouldReceivePromoActionsInfo"),
            "shouldReceiveOrderStatusNotifications": obj.get("shouldReceiveOrderStatusNotifications"),
            "gender": obj.get("gender")
        })
        return _obj


