# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class NomenclatureMenuRequest(BaseModel):
    """
    Request for menu by id.
    """ # noqa: E501
    external_menu_id: StrictStr = Field(description="External menu id                Can be obtained by `api/2/menu` operation.", alias="externalMenuId")
    organization_ids: List[UUID] = Field(description="Organization IDs.                Can be obtained by `/api/1/organizations` operation.", alias="organizationIds")
    price_category_id: Optional[StrictStr] = Field(default=None, description="Price category id.                Can be obtained by `api/2/menu` operation.", alias="priceCategoryId")
    version: Optional[StrictInt] = Field(default=None, description="Version of the result data model.")
    language: Optional[StrictStr] = Field(default=None, description="Language of the external menu.")
    async_mode: Optional[StrictBool] = Field(default=None, description="Async Mode.", alias="asyncMode")
    start_revision: Optional[StrictInt] = Field(default=None, description="Start revision.", alias="startRevision")
    __properties: ClassVar[List[str]] = ["externalMenuId", "organizationIds", "priceCategoryId", "version", "language", "asyncMode", "startRevision"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NomenclatureMenuRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if price_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.price_category_id is None and "price_category_id" in self.model_fields_set:
            _dict['priceCategoryId'] = None

        # set to None if version (nullable) is None
        # and model_fields_set contains the field
        if self.version is None and "version" in self.model_fields_set:
            _dict['version'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if start_revision (nullable) is None
        # and model_fields_set contains the field
        if self.start_revision is None and "start_revision" in self.model_fields_set:
            _dict['startRevision'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NomenclatureMenuRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "externalMenuId": obj.get("externalMenuId"),
            "organizationIds": obj.get("organizationIds"),
            "priceCategoryId": obj.get("priceCategoryId"),
            "version": obj.get("version"),
            "language": obj.get("language"),
            "asyncMode": obj.get("asyncMode"),
            "startRevision": obj.get("startRevision")
        })
        return _obj


