# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from iikocloud_client.models.orders_common_order_status import OrdersCommonOrderStatus
from typing import Optional, Set
from typing_extensions import Self

class TableOrdersRequestGetTableOrdersByTableRequest(BaseModel):
    """
    Request for information about orders using table IDs.
    """ # noqa: E501
    source_keys: Optional[List[StrictStr]] = Field(default=None, description="Source keys.", alias="sourceKeys")
    organization_ids: List[UUID] = Field(description="Organization ID.                Can be obtained by `/api/1/organizations` operation.", alias="organizationIds")
    table_ids: List[UUID] = Field(description="Table IDs.                Can be obtained by `/api/1/reserve/available_restaurant_sections` operation.", alias="tableIds")
    statuses: Optional[List[OrdersCommonOrderStatus]] = Field(default=None, description="Order statuses.")
    date_from: Optional[StrictStr] = Field(default=None, description="Order creation date (terminal time zone). Lower limit.                Order details are stored for 90 days.", alias="dateFrom")
    date_to: Optional[StrictStr] = Field(default=None, description="Order creation date (terminal time zone). Upper limit.", alias="dateTo")
    __properties: ClassVar[List[str]] = ["sourceKeys", "organizationIds", "tableIds", "statuses", "dateFrom", "dateTo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableOrdersRequestGetTableOrdersByTableRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if source_keys (nullable) is None
        # and model_fields_set contains the field
        if self.source_keys is None and "source_keys" in self.model_fields_set:
            _dict['sourceKeys'] = None

        # set to None if statuses (nullable) is None
        # and model_fields_set contains the field
        if self.statuses is None and "statuses" in self.model_fields_set:
            _dict['statuses'] = None

        # set to None if date_from (nullable) is None
        # and model_fields_set contains the field
        if self.date_from is None and "date_from" in self.model_fields_set:
            _dict['dateFrom'] = None

        # set to None if date_to (nullable) is None
        # and model_fields_set contains the field
        if self.date_to is None and "date_to" in self.model_fields_set:
            _dict['dateTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableOrdersRequestGetTableOrdersByTableRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sourceKeys": obj.get("sourceKeys"),
            "organizationIds": obj.get("organizationIds"),
            "tableIds": obj.get("tableIds"),
            "statuses": obj.get("statuses"),
            "dateFrom": obj.get("dateFrom"),
            "dateTo": obj.get("dateTo")
        })
        return _obj


