# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from iikocloud_client.models.transport_stop_lists_web_hook_on_stop_list_change_data import TransportStopListsWebHookOnStopListChangeData
from typing import Optional, Set
from typing_extensions import Self

class TransportWebHooksStopListUpdateWebHookEventInfo(BaseModel):
    """
    WebHook notification about stop list update.
    """ # noqa: E501
    event_type: Optional[StrictStr] = Field(default=None, description="Event type.", alias="eventType")
    event_time: Optional[StrictStr] = Field(default=None, description="Event date and time (UTC).", alias="eventTime")
    organization_id: Optional[StrictStr] = Field(default=None, description="Organization ID.                Can be obtained by `/api/1/organizations` operation.", alias="organizationId")
    correlation_id: Optional[StrictStr] = Field(default=None, description="Operation ID.", alias="correlationId")
    event_info: Optional[TransportStopListsWebHookOnStopListChangeData] = Field(default=None, description="Event details.", alias="eventInfo")
    __properties: ClassVar[List[str]] = ["eventType", "eventTime", "organizationId", "correlationId", "eventInfo"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['StopListUpdate']):
            raise ValueError("must be one of enum values ('StopListUpdate')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransportWebHooksStopListUpdateWebHookEventInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of event_info
        if self.event_info:
            _dict['eventInfo'] = self.event_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransportWebHooksStopListUpdateWebHookEventInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventType": obj.get("eventType"),
            "eventTime": obj.get("eventTime"),
            "organizationId": obj.get("organizationId"),
            "correlationId": obj.get("correlationId"),
            "eventInfo": TransportStopListsWebHookOnStopListChangeData.from_dict(obj["eventInfo"]) if obj.get("eventInfo") is not None else None
        })
        return _obj


