# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from iikocloud_client.models.delivery_order_create_address import DeliveryOrderCreateAddress
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AddressCity(DeliveryOrderCreateAddress):
    """
    AddressCity
    """ # noqa: E501
    doorphone: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=10)]] = Field(default=None, description="Intercom.")
    entrance: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=10)]] = Field(default=None, description="Entrance.")
    flat: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=10)]] = Field(default=None, description="Apartment.")
    floor: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=10)]] = Field(default=None, description="Floor.")
    line1: Annotated[str, Field(min_length=0, strict=True, max_length=250)] = Field(description="Address line 1.  Contains the primary address information.   > Allowed from version `8.7.6`.")
    region_id: Optional[UUID] = Field(default=None, description="Delivery area ID.", alias="regionId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "doorphone", "entrance", "flat", "floor", "line1", "regionId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddressCity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if doorphone (nullable) is None
        # and model_fields_set contains the field
        if self.doorphone is None and "doorphone" in self.model_fields_set:
            _dict['doorphone'] = None

        # set to None if entrance (nullable) is None
        # and model_fields_set contains the field
        if self.entrance is None and "entrance" in self.model_fields_set:
            _dict['entrance'] = None

        # set to None if flat (nullable) is None
        # and model_fields_set contains the field
        if self.flat is None and "flat" in self.model_fields_set:
            _dict['flat'] = None

        # set to None if floor (nullable) is None
        # and model_fields_set contains the field
        if self.floor is None and "floor" in self.model_fields_set:
            _dict['floor'] = None

        # set to None if region_id (nullable) is None
        # and model_fields_set contains the field
        if self.region_id is None and "region_id" in self.model_fields_set:
            _dict['regionId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddressCity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "doorphone": obj.get("doorphone"),
            "entrance": obj.get("entrance"),
            "flat": obj.get("flat"),
            "floor": obj.get("floor"),
            "line1": obj.get("line1"),
            "regionId": obj.get("regionId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


