# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from iikocloud_client.models.combo_component_product import ComboComponentProduct
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComboComponentGroup(BaseModel):
    """
    Combo meal component group (e.g. \"Burger\", \"Drink\", \"Fries\").  Stored inline with original UUIDs for compatibility with external systems.
    """ # noqa: E501
    id: UUID = Field(description="Unique group ID (original UUID).")
    is_main_group: Optional[StrictBool] = Field(default=None, description="Whether the group is the main one (primary combo product).  The main group usually determines the combo name.", alias="isMainGroup")
    name: StrictStr = Field(description="Group name (e.g. \"Drink\").")
    products: Optional[List[ComboComponentProduct]] = Field(default=None, description="List of products available for selection in this group.  Contains combo-specific prices (different from retail prices).")
    skip_step: Optional[StrictBool] = Field(default=None, description="Skip selection step in UI (auto-select the only/default product).  Used for mandatory components without choice.", alias="skipStep")
    __properties: ClassVar[List[str]] = ["id", "isMainGroup", "name", "products", "skipStep"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComboComponentGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in products (list)
        _items = []
        if self.products:
            for _item_products in self.products:
                if _item_products:
                    _items.append(_item_products.to_dict())
            _dict['products'] = _items
        # set to None if products (nullable) is None
        # and model_fields_set contains the field
        if self.products is None and "products" in self.model_fields_set:
            _dict['products'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComboComponentGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "isMainGroup": obj.get("isMainGroup"),
            "name": obj.get("name"),
            "products": [ComboComponentProduct.from_dict(_item) for _item in obj["products"]] if obj.get("products") is not None else None,
            "skipStep": obj.get("skipStep")
        })
        return _obj


