# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iikocloud_client.models.image import Image
from iikocloud_client.models.items_group import ItemsGroup
from iikocloud_client.models.menu_v3_allergen_group import MenuV3AllergenGroup
from iikocloud_client.models.menu_v3_combo import MenuV3Combo
from iikocloud_client.models.menu_v3_customer_tag_group import MenuV3CustomerTagGroup
from iikocloud_client.models.menu_v3_modifier import MenuV3Modifier
from iikocloud_client.models.menu_v3_product import MenuV3Product
from iikocloud_client.models.menu_v3_tax_category import MenuV3TaxCategory
from iikocloud_client.models.product_category import ProductCategory
from iikocloud_client.models.schedule import Schedule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MenuV3(BaseModel):
    """
    Menu structure.
    """ # noqa: E501
    allergen_groups: Optional[List[MenuV3AllergenGroup]] = Field(default=None, description="Allergen groups.", alias="allergenGroups")
    button_image_url: Optional[StrictStr] = Field(default=None, description="Button image URL.", alias="buttonImageUrl")
    combos: Optional[List[MenuV3Combo]] = Field(default=None, description="Combo meals.")
    customer_tag_groups: Optional[List[MenuV3CustomerTagGroup]] = Field(default=None, description="Customer tag groups.", alias="customerTagGroups")
    description: Optional[StrictStr] = Field(default=None, description="Menu description.")
    id: StrictStr = Field(description="Menu ID.")
    image: Optional[Image] = Field(default=None, description="Menu image. Replaces ButtonImageUrl.")
    items_groups: Optional[List[ItemsGroup]] = Field(default=None, description="Item groups.", alias="itemsGroups")
    modifiers: Optional[List[MenuV3Modifier]] = Field(default=None, description="Modifiers.")
    name: StrictStr = Field(description="Menu name.")
    product_categories: Optional[List[ProductCategory]] = Field(default=None, description="Product categories.", alias="productCategories")
    products: Optional[List[MenuV3Product]] = Field(default=None, description="Products.")
    schedules: Optional[List[Schedule]] = Field(default=None, description="Schedules.")
    tax_categories: Optional[List[MenuV3TaxCategory]] = Field(default=None, description="Tax categories.", alias="taxCategories")
    __properties: ClassVar[List[str]] = ["allergenGroups", "buttonImageUrl", "combos", "customerTagGroups", "description", "id", "image", "itemsGroups", "modifiers", "name", "productCategories", "products", "schedules", "taxCategories"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MenuV3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in allergen_groups (list)
        _items = []
        if self.allergen_groups:
            for _item_allergen_groups in self.allergen_groups:
                if _item_allergen_groups:
                    _items.append(_item_allergen_groups.to_dict())
            _dict['allergenGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in combos (list)
        _items = []
        if self.combos:
            for _item_combos in self.combos:
                if _item_combos:
                    _items.append(_item_combos.to_dict())
            _dict['combos'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in customer_tag_groups (list)
        _items = []
        if self.customer_tag_groups:
            for _item_customer_tag_groups in self.customer_tag_groups:
                if _item_customer_tag_groups:
                    _items.append(_item_customer_tag_groups.to_dict())
            _dict['customerTagGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of image
        if self.image:
            _dict['image'] = self.image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items_groups (list)
        _items = []
        if self.items_groups:
            for _item_items_groups in self.items_groups:
                if _item_items_groups:
                    _items.append(_item_items_groups.to_dict())
            _dict['itemsGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in modifiers (list)
        _items = []
        if self.modifiers:
            for _item_modifiers in self.modifiers:
                if _item_modifiers:
                    _items.append(_item_modifiers.to_dict())
            _dict['modifiers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in product_categories (list)
        _items = []
        if self.product_categories:
            for _item_product_categories in self.product_categories:
                if _item_product_categories:
                    _items.append(_item_product_categories.to_dict())
            _dict['productCategories'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in products (list)
        _items = []
        if self.products:
            for _item_products in self.products:
                if _item_products:
                    _items.append(_item_products.to_dict())
            _dict['products'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in schedules (list)
        _items = []
        if self.schedules:
            for _item_schedules in self.schedules:
                if _item_schedules:
                    _items.append(_item_schedules.to_dict())
            _dict['schedules'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tax_categories (list)
        _items = []
        if self.tax_categories:
            for _item_tax_categories in self.tax_categories:
                if _item_tax_categories:
                    _items.append(_item_tax_categories.to_dict())
            _dict['taxCategories'] = _items
        # set to None if allergen_groups (nullable) is None
        # and model_fields_set contains the field
        if self.allergen_groups is None and "allergen_groups" in self.model_fields_set:
            _dict['allergenGroups'] = None

        # set to None if button_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.button_image_url is None and "button_image_url" in self.model_fields_set:
            _dict['buttonImageUrl'] = None

        # set to None if combos (nullable) is None
        # and model_fields_set contains the field
        if self.combos is None and "combos" in self.model_fields_set:
            _dict['combos'] = None

        # set to None if customer_tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.customer_tag_groups is None and "customer_tag_groups" in self.model_fields_set:
            _dict['customerTagGroups'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if image (nullable) is None
        # and model_fields_set contains the field
        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        # set to None if items_groups (nullable) is None
        # and model_fields_set contains the field
        if self.items_groups is None and "items_groups" in self.model_fields_set:
            _dict['itemsGroups'] = None

        # set to None if modifiers (nullable) is None
        # and model_fields_set contains the field
        if self.modifiers is None and "modifiers" in self.model_fields_set:
            _dict['modifiers'] = None

        # set to None if product_categories (nullable) is None
        # and model_fields_set contains the field
        if self.product_categories is None and "product_categories" in self.model_fields_set:
            _dict['productCategories'] = None

        # set to None if products (nullable) is None
        # and model_fields_set contains the field
        if self.products is None and "products" in self.model_fields_set:
            _dict['products'] = None

        # set to None if schedules (nullable) is None
        # and model_fields_set contains the field
        if self.schedules is None and "schedules" in self.model_fields_set:
            _dict['schedules'] = None

        # set to None if tax_categories (nullable) is None
        # and model_fields_set contains the field
        if self.tax_categories is None and "tax_categories" in self.model_fields_set:
            _dict['taxCategories'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MenuV3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allergenGroups": [MenuV3AllergenGroup.from_dict(_item) for _item in obj["allergenGroups"]] if obj.get("allergenGroups") is not None else None,
            "buttonImageUrl": obj.get("buttonImageUrl"),
            "combos": [MenuV3Combo.from_dict(_item) for _item in obj["combos"]] if obj.get("combos") is not None else None,
            "customerTagGroups": [MenuV3CustomerTagGroup.from_dict(_item) for _item in obj["customerTagGroups"]] if obj.get("customerTagGroups") is not None else None,
            "description": obj.get("description"),
            "id": obj.get("id"),
            "image": Image.from_dict(obj["image"]) if obj.get("image") is not None else None,
            "itemsGroups": [ItemsGroup.from_dict(_item) for _item in obj["itemsGroups"]] if obj.get("itemsGroups") is not None else None,
            "modifiers": [MenuV3Modifier.from_dict(_item) for _item in obj["modifiers"]] if obj.get("modifiers") is not None else None,
            "name": obj.get("name"),
            "productCategories": [ProductCategory.from_dict(_item) for _item in obj["productCategories"]] if obj.get("productCategories") is not None else None,
            "products": [MenuV3Product.from_dict(_item) for _item in obj["products"]] if obj.get("products") is not None else None,
            "schedules": [Schedule.from_dict(_item) for _item in obj["schedules"]] if obj.get("schedules") is not None else None,
            "taxCategories": [MenuV3TaxCategory.from_dict(_item) for _item in obj["taxCategories"]] if obj.get("taxCategories") is not None else None
        })
        return _obj


