# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from iikocloud_client.models.common_external_data import CommonExternalData
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from iikocloud_client.models.extended_organization_info import ExtendedOrganizationInfo
    from iikocloud_client.models.simple_organization_info import SimpleOrganizationInfo

class OrganizationInfo(BaseModel):
    """
    Organization details.
    """ # noqa: E501
    code: Optional[StrictStr] = Field(default=None, description="Organization`s code.")
    external_data: Optional[List[CommonExternalData]] = Field(default=None, description="Organization`s external data.", alias="externalData")
    id: UUID = Field(description="Organization ID.                Can be obtained by `/api/1/organizations` operation.")
    name: Optional[StrictStr] = Field(description="Organization name.")
    response_type: StrictStr = Field(alias="responseType")
    __properties: ClassVar[List[str]] = ["code", "externalData", "id", "name", "responseType"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'responseType'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'Extended': 'ExtendedOrganizationInfo','Simple': 'SimpleOrganizationInfo'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[ExtendedOrganizationInfo, SimpleOrganizationInfo]]:
        """Create an instance of OrganizationInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in external_data (list)
        _items = []
        if self.external_data:
            for _item_external_data in self.external_data:
                if _item_external_data:
                    _items.append(_item_external_data.to_dict())
            _dict['externalData'] = _items
        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if external_data (nullable) is None
        # and model_fields_set contains the field
        if self.external_data is None and "external_data" in self.model_fields_set:
            _dict['externalData'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[ExtendedOrganizationInfo, SimpleOrganizationInfo]]:
        """Create an instance of OrganizationInfo from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'ExtendedOrganizationInfo':
            return import_module("iikocloud_client.models.extended_organization_info").ExtendedOrganizationInfo.from_dict(obj)
        if object_type ==  'SimpleOrganizationInfo':
            return import_module("iikocloud_client.models.simple_organization_info").SimpleOrganizationInfo.from_dict(obj)

        raise ValueError("OrganizationInfo failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


