# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from iikocloud_client.models.delivery_order_response_customer import DeliveryOrderResponseCustomer
from iikocloud_client.models.reserve_cancel_reason import ReserveCancelReason
from iikocloud_client.models.reserve_order_response import ReserveOrderResponse
from iikocloud_client.models.reserve_status import ReserveStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Reserve(BaseModel):
    """
    Banquet/reserve.
    """ # noqa: E501
    cancel_reason: Optional[ReserveCancelReason] = Field(default=None, description="The reserve cancellation reason or null if the reserve hasn't been canceled.", alias="cancelReason")
    comment: Optional[StrictStr] = Field(default=None, description="Optional comment for reserve or banquet.")
    customer: DeliveryOrderResponseCustomer = Field(description="Client that placed the reserve.")
    duration_in_minutes: StrictInt = Field(description="Estimated banquet duration.", alias="durationInMinutes")
    estimated_start_time: StrictStr = Field(description="Estimated time when reserve will be closed or banquet will be started.", alias="estimatedStartTime")
    event_type: Optional[StrictStr] = Field(default=None, description="Event type.   > Allowed from version `8.5.6`.", alias="eventType")
    guests_coming_time: Optional[StrictStr] = Field(default=None, description="Time when guests came and reserve was closed or banquet was started.", alias="guestsComingTime")
    guests_count: StrictInt = Field(description="Estimated guests count.", alias="guestsCount")
    order: Optional[ReserveOrderResponse] = Field(default=None, description="Order. Used only at a banquet.")
    phone: Optional[StrictStr] = Field(default=None, description="Telephone number.")
    should_remind: StrictBool = Field(description="Whether to remind staff to prepare table beforehand.", alias="shouldRemind")
    status: ReserveStatus = Field(description="Status of the reserve or banquet.")
    table_ids: List[UUID] = Field(description="Reserved table IDs.", alias="tableIds")
    __properties: ClassVar[List[str]] = ["cancelReason", "comment", "customer", "durationInMinutes", "estimatedStartTime", "eventType", "guestsComingTime", "guestsCount", "order", "phone", "shouldRemind", "status", "tableIds"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Reserve from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # set to None if cancel_reason (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_reason is None and "cancel_reason" in self.model_fields_set:
            _dict['cancelReason'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        # set to None if event_type (nullable) is None
        # and model_fields_set contains the field
        if self.event_type is None and "event_type" in self.model_fields_set:
            _dict['eventType'] = None

        # set to None if guests_coming_time (nullable) is None
        # and model_fields_set contains the field
        if self.guests_coming_time is None and "guests_coming_time" in self.model_fields_set:
            _dict['guestsComingTime'] = None

        # set to None if order (nullable) is None
        # and model_fields_set contains the field
        if self.order is None and "order" in self.model_fields_set:
            _dict['order'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Reserve from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cancelReason": obj.get("cancelReason"),
            "comment": obj.get("comment"),
            "customer": DeliveryOrderResponseCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "durationInMinutes": obj.get("durationInMinutes"),
            "estimatedStartTime": obj.get("estimatedStartTime"),
            "eventType": obj.get("eventType"),
            "guestsComingTime": obj.get("guestsComingTime"),
            "guestsCount": obj.get("guestsCount"),
            "order": ReserveOrderResponse.from_dict(obj["order"]) if obj.get("order") is not None else None,
            "phone": obj.get("phone"),
            "shouldRemind": obj.get("shouldRemind"),
            "status": obj.get("status"),
            "tableIds": obj.get("tableIds")
        })
        return _obj


