# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.outgoing_service_create_request import OutgoingServiceCreateRequest

class TestOutgoingServiceCreateRequest(unittest.TestCase):
    """OutgoingServiceCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutgoingServiceCreateRequest:
        """Test OutgoingServiceCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutgoingServiceCreateRequest`
        """
        model = OutgoingServiceCreateRequest()
        if include_optional:
            return OutgoingServiceCreateRequest(
                comment = '',
                conception = '',
                contract_date = '',
                contract_number = '',
                counteragent = '',
                var_date = '',
                document_id = '',
                due_date = '',
                is_automatic = True,
                is_editable = True,
                items = [
                    iikocloud_client.models.outgoing_service_create_item.OutgoingServiceCreateItem(
                        amount = 1.337, 
                        discount_sum = 1.337, 
                        num = 56, 
                        price = 1.337, 
                        product = '', 
                        revenue_account = '', 
                        split_vat = True, 
                        sum = 1.337, 
                        vat_percent = 1.337, )
                    ],
                number = '',
                organization_id = '',
                revenue_account = ''
            )
        else:
            return OutgoingServiceCreateRequest(
                counteragent = '',
                var_date = '',
                items = [
                    iikocloud_client.models.outgoing_service_create_item.OutgoingServiceCreateItem(
                        amount = 1.337, 
                        discount_sum = 1.337, 
                        num = 56, 
                        price = 1.337, 
                        product = '', 
                        revenue_account = '', 
                        split_vat = True, 
                        sum = 1.337, 
                        vat_percent = 1.337, )
                    ],
                organization_id = '',
        )
        """

    def testOutgoingServiceCreateRequest(self):
        """Test OutgoingServiceCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
