# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.get_olap_report_request import GetOlapReportRequest

class TestGetOlapReportRequest(unittest.TestCase):
    """GetOlapReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOlapReportRequest:
        """Test GetOlapReportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOlapReportRequest`
        """
        model = GetOlapReportRequest()
        if include_optional:
            return GetOlapReportRequest(
                aggregate_fields = [
                    ''
                    ],
                build_summary = True,
                filters = [
                    iikocloud_client.models.olap_filter_doc.OlapFilterDoc(
                        filter_type = '', 
                        from = null, 
                        include_high = True, 
                        include_low = True, 
                        name = '', 
                        period_type = '', 
                        to = null, 
                        values = [
                            ''
                            ], )
                    ],
                group_by_col_fields = [
                    ''
                    ],
                group_by_row_fields = [
                    ''
                    ],
                report_type = ''
            )
        else:
            return GetOlapReportRequest(
                aggregate_fields = [
                    ''
                    ],
                filters = [
                    iikocloud_client.models.olap_filter_doc.OlapFilterDoc(
                        filter_type = '', 
                        from = null, 
                        include_high = True, 
                        include_low = True, 
                        name = '', 
                        period_type = '', 
                        to = null, 
                        values = [
                            ''
                            ], )
                    ],
                report_type = '',
        )
        """

    def testGetOlapReportRequest(self):
        """Test GetOlapReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
