# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.api.drafts_api import DraftsApi


class TestDraftsApi(unittest.IsolatedAsyncioTestCase):
    """DraftsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DraftsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_commit_delivery_draft(self) -> None:
        """Test case for commit_delivery_draft

        Admit order draft changes and send them to Front.
        """
        pass

    async def test_create_delivery_draft(self) -> None:
        """Test case for create_delivery_draft

        Create delivery order draft.
        """
        pass

    async def test_delete_delivery_draft(self) -> None:
        """Test case for delete_delivery_draft

        Delete order draft.
        """
        pass

    async def test_get_delivery_draft_by_id(self) -> None:
        """Test case for get_delivery_draft_by_id

        Retrieve order draft by ID.
        """
        pass

    async def test_get_delivery_drafts_by_filter(self) -> None:
        """Test case for get_delivery_drafts_by_filter

        Retrieve order drafts list by parameters.
        """
        pass

    async def test_lock_delivery_draft(self) -> None:
        """Test case for lock_delivery_draft

        Lock order draft.
        """
        pass

    async def test_save_delivery_draft(self) -> None:
        """Test case for save_delivery_draft

        Update existing delivery order draft.
        """
        pass

    async def test_unlock_delivery_draft(self) -> None:
        """Test case for unlock_delivery_draft

        Unlock order draft.
        """
        pass


if __name__ == '__main__':
    unittest.main()
