# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.orders_by_delivery_date_and_filter_request import OrdersByDeliveryDateAndFilterRequest

class TestOrdersByDeliveryDateAndFilterRequest(unittest.TestCase):
    """OrdersByDeliveryDateAndFilterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrdersByDeliveryDateAndFilterRequest:
        """Test OrdersByDeliveryDateAndFilterRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrdersByDeliveryDateAndFilterRequest`
        """
        model = OrdersByDeliveryDateAndFilterRequest()
        if include_optional:
            return OrdersByDeliveryDateAndFilterRequest(
                cooking_timeout = 56,
                delivery_date_from = '2019-08-24 14:15:22.123',
                delivery_date_to = '2019-08-24 14:15:22.123',
                has_problem = True,
                order_ids = [
                    ''
                    ],
                order_service_type = 'DeliveryByCourier',
                organization_ids = [
                    ''
                    ],
                pos_order_ids = [
                    ''
                    ],
                rows_count = 56,
                search_text = '',
                sort_direction = 'Ascending',
                sort_property = 'Number',
                source_keys = [
                    ''
                    ],
                statuses = [
                    'Unconfirmed'
                    ],
                terminal_group_ids = [
                    ''
                    ],
                time_to_cooking_error_timeout = 56
            )
        else:
            return OrdersByDeliveryDateAndFilterRequest(
                organization_ids = [
                    ''
                    ],
        )
        """

    def testOrdersByDeliveryDateAndFilterRequest(self):
        """Test OrdersByDeliveryDateAndFilterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
