# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.api.discounts_and_promotions_api import DiscountsAndPromotionsApi


class TestDiscountsAndPromotionsApi(unittest.IsolatedAsyncioTestCase):
    """DiscountsAndPromotionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DiscountsAndPromotionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_calculate_loyalty_checkin(self) -> None:
        """Test case for calculate_loyalty_checkin

        Calculate checkin.
        """
        pass

    async def test_get_coupon_info(self) -> None:
        """Test case for get_coupon_info

        Get coupon info.
        """
        pass

    async def test_get_coupon_series(self) -> None:
        """Test case for get_coupon_series

        Get coupon series with non-activated coupons.
        """
        pass

    async def test_get_loyalty_manual_conditions(self) -> None:
        """Test case for get_loyalty_manual_conditions

        Get manual conditions.
        """
        pass

    async def test_get_loyalty_programs(self) -> None:
        """Test case for get_loyalty_programs

        Get programs.
        """
        pass

    async def test_get_non_activated_coupons_by_series(self) -> None:
        """Test case for get_non_activated_coupons_by_series

        Get non-activated coupons
        """
        pass


if __name__ == '__main__':
    unittest.main()
