# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.table_order_response_payload import TableOrderResponsePayload

class TestTableOrderResponsePayload(unittest.TestCase):
    """TableOrderResponsePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableOrderResponsePayload:
        """Test TableOrderResponsePayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableOrderResponsePayload`
        """
        model = TableOrderResponsePayload()
        if include_optional:
            return TableOrderResponsePayload(
                combos = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order_combo.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.OrderCombo(
                        amount = 56, 
                        id = '', 
                        name = '', 
                        price = 1.337, 
                        size = null, 
                        source_id = '', )
                    ],
                conception = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/conception.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.Conception(
                    code = '', 
                    id = '', 
                    name = '', ),
                customer = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/regular_customer.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.RegularCustomer(),
                discounts = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/discount_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.DiscountItem(
                        discount_type = null, 
                        selective_positions = [
                            ''
                            ], 
                        selective_positions_with_sum = [
                            iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/position_with_sum.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.PositionWithSum(
                                position_id = '', 
                                sum = 1.337, )
                            ], 
                        sum = 1.337, )
                    ],
                external_data = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/external_data.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.ExternalData(
                        key = '', 
                        value = '', )
                    ],
                guests_info = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/guests_info.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.GuestsInfo(
                    count = 56, 
                    split_between_persons = True, ),
                items = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.OrderItem(
                        amount = 1.337, 
                        combo_information = null, 
                        comment = '', 
                        deleted = null, 
                        size = null, 
                        status = null, 
                        type = '', 
                        when_printed = '2019-08-24 14:15:22.123', )
                    ],
                loyalty_info = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/loyalty_info.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.LoyaltyInfo(
                    applied_manual_conditions = [
                        ''
                        ], 
                    coupon = '', 
                    dynamic_discounts = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/dynamic_discount.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.DynamicDiscount(
                            manual_condition_id = '', 
                            sum = 1.337, )
                        ], ),
                menu_id = '',
                number = 56,
                order_type = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order_type.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.OrderType(
                    id = '', 
                    name = '', 
                    order_service_type = null, ),
                payments = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/payment_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.PaymentItem(
                        is_external = True, 
                        is_fiscalized_externally = True, 
                        is_preliminary = True, 
                        is_prepay = True, 
                        is_processed_externally = True, 
                        payment_type = null, 
                        sum = 1.337, )
                    ],
                phone = '',
                price_category = iikocloud_client.models.iiko_transport/public_api/contracts/common/price_category.iikoTransport.PublicApi.Contracts.Common.PriceCategory(
                    id = '', 
                    name = '', ),
                processed_payments_sum = 1.337,
                source_key = '',
                split_order_between_cash_registers = 'Disabled',
                status = 'New',
                sum = 1.337,
                tab_name = '',
                table_ids = [
                    ''
                    ],
                terminal_group_id = '',
                tips = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/tips_payment_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.TipsPaymentItem(
                        is_external = True, 
                        is_fiscalized_externally = True, 
                        is_preliminary = True, 
                        is_prepay = True, 
                        is_processed_externally = True, 
                        payment_type = null, 
                        sum = 1.337, 
                        tips_type = null, )
                    ],
                waiter = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/employee.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.Employee(
                    id = '', 
                    name = '', 
                    phone = '', ),
                when_bill_printed = '2019-08-24 14:15:22.123',
                when_closed = '2019-08-24 14:15:22.123',
                when_created = '2019-08-24 14:15:22.123'
            )
        else:
            return TableOrderResponsePayload(
                guests_info = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/guests_info.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.GuestsInfo(
                    count = 56, 
                    split_between_persons = True, ),
                items = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.OrderItem(
                        amount = 1.337, 
                        combo_information = null, 
                        comment = '', 
                        deleted = null, 
                        size = null, 
                        status = null, 
                        type = '', 
                        when_printed = '2019-08-24 14:15:22.123', )
                    ],
                number = 56,
                order_type = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order_type.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.OrderType(
                    id = '', 
                    name = '', 
                    order_service_type = null, ),
                processed_payments_sum = 1.337,
                status = 'New',
                sum = 1.337,
                table_ids = [
                    ''
                    ],
                terminal_group_id = '',
        )
        """

    def testTableOrderResponsePayload(self):
        """Test TableOrderResponsePayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
