# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.corporation_settings import CorporationSettings

class TestCorporationSettings(unittest.TestCase):
    """CorporationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorporationSettings:
        """Test CorporationSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorporationSettings`
        """
        model = CorporationSettings()
        if include_optional:
            return CorporationSettings(
                crm_id = '',
                currency = None,
                default_deviation_action = '',
                default_distribution_algorithm = '',
                delete_zero_production_order_items = True,
                deleted = True,
                description = '',
                document_settings = None,
                gln = '',
                id = '',
                local_id = '',
                money_precision = 56,
                name = '',
                parent = '',
                personal_data_processing_settings = None,
                round_cost_for_guests = True,
                round_price_per_unit_for_guests = True,
                vat_accounting = ''
            )
        else:
            return CorporationSettings(
        )
        """

    def testCorporationSettings(self):
        """Test CorporationSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
