# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.api.public_api_invoice_processing_internal_transfer_api import PublicApiInvoiceProcessingInternalTransferApi


class TestPublicApiInvoiceProcessingInternalTransferApi(unittest.IsolatedAsyncioTestCase):
    """PublicApiInvoiceProcessingInternalTransferApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PublicApiInvoiceProcessingInternalTransferApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_cancel_inventory_internal_transfer(self) -> None:
        """Test case for cancel_inventory_internal_transfer

        Cancel internal transfer act draft
        """
        pass

    async def test_create_inventory_internal_transfer(self) -> None:
        """Test case for create_inventory_internal_transfer

        Create internal transfer act
        """
        pass

    async def test_get_inventory_internal_transfer(self) -> None:
        """Test case for get_inventory_internal_transfer

        Get internal transfer act by identifier
        """
        pass

    async def test_list_inventory_internal_transfers(self) -> None:
        """Test case for list_inventory_internal_transfers

        Export internal transfer acts
        """
        pass

    async def test_post_inventory_internal_transfer(self) -> None:
        """Test case for post_inventory_internal_transfer

        Post internal transfer act
        """
        pass

    async def test_unpost_inventory_internal_transfer(self) -> None:
        """Test case for unpost_inventory_internal_transfer

        Unpost internal transfer act
        """
        pass

    async def test_update_inventory_internal_transfer(self) -> None:
        """Test case for update_inventory_internal_transfer

        Edit internal transfer act
        """
        pass


if __name__ == '__main__':
    unittest.main()
