# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.order_info import OrderInfo

class TestOrderInfo(unittest.TestCase):
    """OrderInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderInfo:
        """Test OrderInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderInfo`
        """
        model = OrderInfo()
        if include_optional:
            return OrderInfo(
                creation_status = 'Success',
                error_info = iikocloud_client.models.iiko_transport/public_api/contracts/errors/error_info.iikoTransport.PublicApi.Contracts.Errors.ErrorInfo(
                    additional_data = null, 
                    code = null, 
                    description = '', 
                    error_reason = '', 
                    message = '', ),
                external_number = '',
                id = '',
                order = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.Order(
                    cancel_info = null, 
                    combos = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order_combo.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.OrderCombo(
                            amount = 56, 
                            id = '', 
                            name = '', 
                            price = 1.337, 
                            size = null, 
                            source_id = '', )
                        ], 
                    comment = '', 
                    complete_before = '2019-08-24 14:15:22.123', 
                    conception = null, 
                    cooking_start_time = '2019-08-24 14:15:22.123', 
                    courier_info = null, 
                    customer = null, 
                    delivery_duration = 56, 
                    delivery_point = null, 
                    delivery_zone = '', 
                    discounts = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/discount_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.DiscountItem(
                            discount_type = null, 
                            selective_positions = [
                                ''
                                ], 
                            selective_positions_with_sum = [
                                iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/position_with_sum.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.PositionWithSum(
                                    position_id = '', 
                                    sum = 1.337, )
                                ], 
                            sum = 1.337, )
                        ], 
                    estimated_time = '2019-08-24 14:15:22.123', 
                    external_courier_service = null, 
                    external_data = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/external_data.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.ExternalData(
                            key = '', 
                            value = '', )
                        ], 
                    guests_info = null, 
                    index_in_courier_route = 56, 
                    is_asap = True, 
                    is_deleted = True, 
                    items = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/order_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.OrderItem(
                            amount = 1.337, 
                            combo_information = null, 
                            comment = '', 
                            deleted = null, 
                            size = null, 
                            status = null, 
                            type = '', 
                            when_printed = '2019-08-24 14:15:22.123', )
                        ], 
                    locked_at = '2019-08-24 14:15:22.123', 
                    loyalty_info = null, 
                    marketing_source = null, 
                    menu_id = '', 
                    moved_from_delivery_id = '', 
                    moved_from_organization_id = '', 
                    moved_from_terminal_group_id = '', 
                    moved_to_delivery_id = '', 
                    moved_to_organization_id = '', 
                    moved_to_terminal_group_id = '', 
                    number = 56, 
                    operator = null, 
                    order_type = null, 
                    parent_delivery_id = '', 
                    payments = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/payment_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.PaymentItem(
                            is_external = True, 
                            is_fiscalized_externally = True, 
                            is_preliminary = True, 
                            is_prepay = True, 
                            is_processed_externally = True, 
                            payment_type = null, 
                            sum = 1.337, )
                        ], 
                    phone = '', 
                    phone_extension = '', 
                    price_category = null, 
                    problem = null, 
                    processed_payments_sum = 1.337, 
                    source_key = '', 
                    status = null, 
                    sum = 1.337, 
                    terminal_group_id = '', 
                    tips = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/response/order/tips_payment_item.iikoTransport.PublicApi.Contracts.Deliveries.Response.Order.TipsPaymentItem(
                            is_external = True, 
                            is_fiscalized_externally = True, 
                            is_preliminary = True, 
                            is_prepay = True, 
                            is_processed_externally = True, 
                            payment_type = null, 
                            sum = 1.337, 
                            tips_type = null, )
                        ], 
                    tracking_link = '', 
                    when_bill_printed = '2019-08-24 14:15:22.123', 
                    when_closed = '2019-08-24 14:15:22.123', 
                    when_confirmed = '2019-08-24 14:15:22.123', 
                    when_cooking_completed = '2019-08-24 14:15:22.123', 
                    when_created = '2019-08-24 14:15:22.123', 
                    when_delivered = '2019-08-24 14:15:22.123', 
                    when_packed = '2019-08-24 14:15:22.123', 
                    when_printed = '2019-08-24 14:15:22.123', 
                    when_received_by_api = '2019-08-24 14:15:22.123', 
                    when_received_from_front = '2019-08-24 14:15:22.123', 
                    when_sended = '2019-08-24 14:15:22.123', ),
                organization_id = '',
                pos_id = '',
                timestamp = 56
            )
        else:
            return OrderInfo(
                creation_status = 'Success',
                id = '',
                organization_id = '',
                timestamp = 56,
        )
        """

    def testOrderInfo(self):
        """Test OrderInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
