# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.delivery_order import DeliveryOrder

class TestDeliveryOrder(unittest.TestCase):
    """DeliveryOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryOrder:
        """Test DeliveryOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveryOrder`
        """
        model = DeliveryOrder()
        if include_optional:
            return DeliveryOrder(
                cheque_additional_info = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/common/cheque_additional_info.iikoTransport.PublicApi.Contracts.Deliveries.Common.ChequeAdditionalInfo(
                    email = '', 
                    is_internet_payment = True, 
                    need_receipt = True, 
                    phone = '01234567', 
                    retail_address = '', 
                    settlement_place = '', ),
                combos = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/combo.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.Combo(
                        amount = 56, 
                        id = '', 
                        name = '', 
                        price = 1.337, 
                        program_id = '', 
                        size_id = '', 
                        source_id = '', )
                    ],
                comment = '',
                complete_before = '2019-08-24 14:15:22.123',
                customer = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/customer.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.Customer(
                    type = '', ),
                delivery_duration = 56,
                delivery_point = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/delivery_point.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.DeliveryPoint(
                    address = null, 
                    comment = '', 
                    coordinates = null, 
                    external_cartography_id = '', ),
                delivery_zone = '',
                discounts_info = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/discounts_info.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.DiscountsInfo(
                    card = null, 
                    discounts = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/discount.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.Discount(
                            type = '', )
                        ], 
                    fixed_loyalty_discounts = True, ),
                external_data = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/external_data.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.ExternalData(
                        is_public = True, 
                        key = '', 
                        value = '', )
                    ],
                external_number = '',
                guests = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/guests.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.Guests(
                    count = 56, 
                    split_between_persons = True, ),
                id = '',
                items = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/order_item.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.OrderItem(
                        amount = 0, 
                        combo_information = null, 
                        comment = '', 
                        product_size_id = '', 
                        type = '', )
                    ],
                loyalty_info = iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/loyalty_info.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.LoyaltyInfo(
                    applicable_manual_conditions = [
                        ''
                        ], 
                    coupon = '', 
                    dynamic_discounts = [
                        iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/dynamic_discount.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.DynamicDiscount(
                            manual_condition_id = '', 
                            sum = 1.337, )
                        ], ),
                marketing_source_id = '',
                menu_id = '',
                operator_id = '',
                order_service_type = 'DeliveryByCourier',
                order_type_id = '',
                payments = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/payment.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.Payment(
                        is_fiscalized_externally = True, 
                        is_prepay = True, 
                        is_processed_externally = True, 
                        payment_additional_data = null, 
                        payment_type_id = '', 
                        payment_type_kind = '', 
                        sum = 0, )
                    ],
                phone = '01234567',
                phone_extension = '0',
                price_category_id = '',
                source_key = '',
                tips = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/tips_payment.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.TipsPayment(
                        is_fiscalized_externally = True, 
                        is_prepay = True, 
                        is_processed_externally = True, 
                        payment_additional_data = null, 
                        payment_type_id = '', 
                        payment_type_kind = '', 
                        sum = 0, 
                        tips_type_id = '', )
                    ]
            )
        else:
            return DeliveryOrder(
                items = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/deliveries/request/create_order/order_item.iikoTransport.PublicApi.Contracts.Deliveries.Request.CreateOrder.OrderItem(
                        amount = 0, 
                        combo_information = null, 
                        comment = '', 
                        product_size_id = '', 
                        type = '', )
                    ],
                phone = '01234567',
        )
        """

    def testDeliveryOrder(self):
        """Test DeliveryOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
