# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.removal_types_response import RemovalTypesResponse

class TestRemovalTypesResponse(unittest.TestCase):
    """RemovalTypesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemovalTypesResponse:
        """Test RemovalTypesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemovalTypesResponse`
        """
        model = RemovalTypesResponse()
        if include_optional:
            return RemovalTypesResponse(
                correlation_id = '',
                removal_types = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/removal_types/removal_type.iikoTransport.PublicApi.Contracts.RemovalTypes.RemovalType(
                        can_writeoff_to_cafe = True, 
                        can_writeoff_to_user = True, 
                        can_writeoff_to_waiter = True, 
                        comment = '', 
                        id = '', 
                        is_deleted = True, 
                        manual = True, 
                        name = '', 
                        reason_required = True, )
                    ]
            )
        else:
            return RemovalTypesResponse(
                correlation_id = '',
                removal_types = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/removal_types/removal_type.iikoTransport.PublicApi.Contracts.RemovalTypes.RemovalType(
                        can_writeoff_to_cafe = True, 
                        can_writeoff_to_user = True, 
                        can_writeoff_to_waiter = True, 
                        comment = '', 
                        id = '', 
                        is_deleted = True, 
                        manual = True, 
                        name = '', 
                        reason_required = True, )
                    ],
        )
        """

    def testRemovalTypesResponse(self):
        """Test RemovalTypesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
