# coding: utf-8

"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iikocloud_client.models.menu_v3_product import MenuV3Product

class TestMenuV3Product(unittest.TestCase):
    """MenuV3Product unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MenuV3Product:
        """Test MenuV3Product
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MenuV3Product`
        """
        model = MenuV3Product()
        if include_optional:
            return MenuV3Product(
                barcodes = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/nomenclature_v3/barcode_info.iikoTransport.PublicApi.Contracts.NomenclatureV3.BarcodeInfo(
                        barcode = '', 
                        container = '', 
                        product_fiscal_code = '', )
                    ],
                can_set_open_price = True,
                customer_tag_groups = [
                    iikocloud_client.models.iiko_transport/public_api/contracts/nomenclature_v3/customer_tag_group_item.iikoTransport.PublicApi.Contracts.NomenclatureV3.CustomerTagGroupItem(
                        customer_tag_group_id = '', 
                        selected_tag_ids = [
                            ''
                            ], )
                    ],
                id = '',
                is_marked = True,
                measure_unit = '',
                modifier_schema_id = '',
                modifier_schema_name = '',
                order_item_type = 'Product',
                outer_ean_code = '',
                payment_subject_code = '',
                product_category_id = '',
                sku = '',
                splittable = True,
                tax_category_id = '',
                type = 'DISH',
                use_balance_for_sell = True
            )
        else:
            return MenuV3Product(
                id = '',
                sku = '',
        )
        """

    def testMenuV3Product(self):
        """Test MenuV3Product"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
