# flake8: noqa

# import apis into api package
from iiko_cloud_client.api.addresses_api import AddressesApi
from iiko_cloud_client.api.authorization_api import AuthorizationApi
from iiko_cloud_client.api.banquets_reserves_api import BanquetsReservesApi
from iiko_cloud_client.api.customer_categories_api import CustomerCategoriesApi
from iiko_cloud_client.api.customers_api import CustomersApi
from iiko_cloud_client.api.deliveries_create_and_update_api import DeliveriesCreateAndUpdateApi
from iiko_cloud_client.api.deliveries_retrieve_api import DeliveriesRetrieveApi
from iiko_cloud_client.api.delivery_restrictions_api import DeliveryRestrictionsApi
from iiko_cloud_client.api.deprecated_api import DeprecatedApi
from iiko_cloud_client.api.dictionaries_api import DictionariesApi
from iiko_cloud_client.api.discounts_and_promotions_api import DiscountsAndPromotionsApi
from iiko_cloud_client.api.drafts_api import DraftsApi
from iiko_cloud_client.api.employees_api import EmployeesApi
from iiko_cloud_client.api.marketing_sources_api import MarketingSourcesApi
from iiko_cloud_client.api.menu_api import MenuApi
from iiko_cloud_client.api.messages_api import MessagesApi
from iiko_cloud_client.api.notifications_api import NotificationsApi
from iiko_cloud_client.api.operations_api import OperationsApi
from iiko_cloud_client.api.orders_api import OrdersApi
from iiko_cloud_client.api.organizations_api import OrganizationsApi
from iiko_cloud_client.api.report_api import ReportApi
from iiko_cloud_client.api.terminal_groups_api import TerminalGroupsApi
from iiko_cloud_client.api.webhooks_api import WebhooksApi

