"""
    iikoCloud API

    <h3>Description of common data formats:</h3><b>uuid</b> - string in UUID(universally unique identifier).<br/>Examples: <i>550e8400-e29b-41d4-a716-446655440000, b090de0b-8550-6e17-70b2-bbba152bcbd3</i><br/><br/><b>date-time</b> - date and time string in custom string format <b>yyyy-MM-dd HH:mm:ss.fff</b>.<br/>Examples: <i>2017-04-29 20:45:00.000, 2018-01-01 01:01:30.123</i>

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt
from typing import Optional
from typing_extensions import Annotated
from iikocloud_client.models.nomenclature_category_create_request import NomenclatureCategoryCreateRequest
from iikocloud_client.models.nomenclature_category_delete_request import NomenclatureCategoryDeleteRequest
from iikocloud_client.models.nomenclature_category_list_request import NomenclatureCategoryListRequest
from iikocloud_client.models.nomenclature_category_list_response import NomenclatureCategoryListResponse
from iikocloud_client.models.nomenclature_category_restore_request import NomenclatureCategoryRestoreRequest
from iikocloud_client.models.nomenclature_category_update_request import NomenclatureCategoryUpdateRequest
from iikocloud_client.models.nomenclature_category_write_response import NomenclatureCategoryWriteResponse

from iikocloud_client.api_client import ApiClient, RequestSerialized
from iikocloud_client.api_response import ApiResponse
from iikocloud_client.rest import RESTResponseType


class NomenclatureNomenclatureCategoryApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def create_nomenclature_product_category(
        self,
        nomenclature_category_create_request: Annotated[NomenclatureCategoryCreateRequest, Field(description="Request body for creating a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NomenclatureCategoryWriteResponse:
        """Create a product category

        Creates a new product category. Only the `name` field is required. 

        :param nomenclature_category_create_request: Request body for creating a product category (required)
        :type nomenclature_category_create_request: NomenclatureCategoryCreateRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_nomenclature_product_category_serialize(
            nomenclature_category_create_request=nomenclature_category_create_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def create_nomenclature_product_category_with_http_info(
        self,
        nomenclature_category_create_request: Annotated[NomenclatureCategoryCreateRequest, Field(description="Request body for creating a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NomenclatureCategoryWriteResponse]:
        """Create a product category

        Creates a new product category. Only the `name` field is required. 

        :param nomenclature_category_create_request: Request body for creating a product category (required)
        :type nomenclature_category_create_request: NomenclatureCategoryCreateRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_nomenclature_product_category_serialize(
            nomenclature_category_create_request=nomenclature_category_create_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def create_nomenclature_product_category_without_preload_content(
        self,
        nomenclature_category_create_request: Annotated[NomenclatureCategoryCreateRequest, Field(description="Request body for creating a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create a product category

        Creates a new product category. Only the `name` field is required. 

        :param nomenclature_category_create_request: Request body for creating a product category (required)
        :type nomenclature_category_create_request: NomenclatureCategoryCreateRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_nomenclature_product_category_serialize(
            nomenclature_category_create_request=nomenclature_category_create_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_nomenclature_product_category_serialize(
        self,
        nomenclature_category_create_request,
        timeout,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if timeout is not None:
            _header_params['Timeout'] = timeout
        # process the form parameters
        # process the body parameter
        if nomenclature_category_create_request is not None:
            _body_params = nomenclature_category_create_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/nomenclature/v1/nomenclature/category/create',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def delete_nomenclature_product_category(
        self,
        nomenclature_category_delete_request: Annotated[NomenclatureCategoryDeleteRequest, Field(description="Request body for deleting a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NomenclatureCategoryWriteResponse:
        """Delete a product category

        Soft-deletes a product category by UUID. Already deleted categories cannot be deleted again. 

        :param nomenclature_category_delete_request: Request body for deleting a product category (required)
        :type nomenclature_category_delete_request: NomenclatureCategoryDeleteRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_nomenclature_product_category_serialize(
            nomenclature_category_delete_request=nomenclature_category_delete_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def delete_nomenclature_product_category_with_http_info(
        self,
        nomenclature_category_delete_request: Annotated[NomenclatureCategoryDeleteRequest, Field(description="Request body for deleting a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NomenclatureCategoryWriteResponse]:
        """Delete a product category

        Soft-deletes a product category by UUID. Already deleted categories cannot be deleted again. 

        :param nomenclature_category_delete_request: Request body for deleting a product category (required)
        :type nomenclature_category_delete_request: NomenclatureCategoryDeleteRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_nomenclature_product_category_serialize(
            nomenclature_category_delete_request=nomenclature_category_delete_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def delete_nomenclature_product_category_without_preload_content(
        self,
        nomenclature_category_delete_request: Annotated[NomenclatureCategoryDeleteRequest, Field(description="Request body for deleting a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Delete a product category

        Soft-deletes a product category by UUID. Already deleted categories cannot be deleted again. 

        :param nomenclature_category_delete_request: Request body for deleting a product category (required)
        :type nomenclature_category_delete_request: NomenclatureCategoryDeleteRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_nomenclature_product_category_serialize(
            nomenclature_category_delete_request=nomenclature_category_delete_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _delete_nomenclature_product_category_serialize(
        self,
        nomenclature_category_delete_request,
        timeout,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if timeout is not None:
            _header_params['Timeout'] = timeout
        # process the form parameters
        # process the body parameter
        if nomenclature_category_delete_request is not None:
            _body_params = nomenclature_category_delete_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/nomenclature/v1/nomenclature/category/delete',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def list_nomenclature_product_categories(
        self,
        nomenclature_category_list_request: Annotated[NomenclatureCategoryListRequest, Field(description="Request body for listing product categories")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NomenclatureCategoryListResponse:
        """Get a list of product categories

        Returns a list of product categories. The list can be narrowed by passing the `ids` array; pass `includeDeleted: true` to include soft-deleted categories. Pagination is supported via `limit` / `offset`: `limit` is the maximum number of categories in the response page, `offset` is the number of categories to skip from the beginning. If `limit` is not passed or is <= 0, all matching categories are returned. The `totalCount` field always contains the total number of matching categories (before pagination). 

        :param nomenclature_category_list_request: Request body for listing product categories (required)
        :type nomenclature_category_list_request: NomenclatureCategoryListRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_nomenclature_product_categories_serialize(
            nomenclature_category_list_request=nomenclature_category_list_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryListResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def list_nomenclature_product_categories_with_http_info(
        self,
        nomenclature_category_list_request: Annotated[NomenclatureCategoryListRequest, Field(description="Request body for listing product categories")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NomenclatureCategoryListResponse]:
        """Get a list of product categories

        Returns a list of product categories. The list can be narrowed by passing the `ids` array; pass `includeDeleted: true` to include soft-deleted categories. Pagination is supported via `limit` / `offset`: `limit` is the maximum number of categories in the response page, `offset` is the number of categories to skip from the beginning. If `limit` is not passed or is <= 0, all matching categories are returned. The `totalCount` field always contains the total number of matching categories (before pagination). 

        :param nomenclature_category_list_request: Request body for listing product categories (required)
        :type nomenclature_category_list_request: NomenclatureCategoryListRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_nomenclature_product_categories_serialize(
            nomenclature_category_list_request=nomenclature_category_list_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryListResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def list_nomenclature_product_categories_without_preload_content(
        self,
        nomenclature_category_list_request: Annotated[NomenclatureCategoryListRequest, Field(description="Request body for listing product categories")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get a list of product categories

        Returns a list of product categories. The list can be narrowed by passing the `ids` array; pass `includeDeleted: true` to include soft-deleted categories. Pagination is supported via `limit` / `offset`: `limit` is the maximum number of categories in the response page, `offset` is the number of categories to skip from the beginning. If `limit` is not passed or is <= 0, all matching categories are returned. The `totalCount` field always contains the total number of matching categories (before pagination). 

        :param nomenclature_category_list_request: Request body for listing product categories (required)
        :type nomenclature_category_list_request: NomenclatureCategoryListRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_nomenclature_product_categories_serialize(
            nomenclature_category_list_request=nomenclature_category_list_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryListResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_nomenclature_product_categories_serialize(
        self,
        nomenclature_category_list_request,
        timeout,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if timeout is not None:
            _header_params['Timeout'] = timeout
        # process the form parameters
        # process the body parameter
        if nomenclature_category_list_request is not None:
            _body_params = nomenclature_category_list_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/nomenclature/v1/nomenclature/category/list',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def restore_nomenclature_product_category(
        self,
        nomenclature_category_restore_request: Annotated[NomenclatureCategoryRestoreRequest, Field(description="Request body for restoring a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NomenclatureCategoryWriteResponse:
        """Restore a product category

        Restores a previously deleted product category by UUID. Only deleted categories can be restored. 

        :param nomenclature_category_restore_request: Request body for restoring a product category (required)
        :type nomenclature_category_restore_request: NomenclatureCategoryRestoreRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._restore_nomenclature_product_category_serialize(
            nomenclature_category_restore_request=nomenclature_category_restore_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def restore_nomenclature_product_category_with_http_info(
        self,
        nomenclature_category_restore_request: Annotated[NomenclatureCategoryRestoreRequest, Field(description="Request body for restoring a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NomenclatureCategoryWriteResponse]:
        """Restore a product category

        Restores a previously deleted product category by UUID. Only deleted categories can be restored. 

        :param nomenclature_category_restore_request: Request body for restoring a product category (required)
        :type nomenclature_category_restore_request: NomenclatureCategoryRestoreRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._restore_nomenclature_product_category_serialize(
            nomenclature_category_restore_request=nomenclature_category_restore_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def restore_nomenclature_product_category_without_preload_content(
        self,
        nomenclature_category_restore_request: Annotated[NomenclatureCategoryRestoreRequest, Field(description="Request body for restoring a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Restore a product category

        Restores a previously deleted product category by UUID. Only deleted categories can be restored. 

        :param nomenclature_category_restore_request: Request body for restoring a product category (required)
        :type nomenclature_category_restore_request: NomenclatureCategoryRestoreRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._restore_nomenclature_product_category_serialize(
            nomenclature_category_restore_request=nomenclature_category_restore_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _restore_nomenclature_product_category_serialize(
        self,
        nomenclature_category_restore_request,
        timeout,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if timeout is not None:
            _header_params['Timeout'] = timeout
        # process the form parameters
        # process the body parameter
        if nomenclature_category_restore_request is not None:
            _body_params = nomenclature_category_restore_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/nomenclature/v1/nomenclature/category/restore',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def update_nomenclature_product_category(
        self,
        nomenclature_category_update_request: Annotated[NomenclatureCategoryUpdateRequest, Field(description="Request body for updating a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NomenclatureCategoryWriteResponse:
        """Update a product category

        Updates an existing product category. Both `id` (UUID of the category to update) and `name` (new name) are required. 

        :param nomenclature_category_update_request: Request body for updating a product category (required)
        :type nomenclature_category_update_request: NomenclatureCategoryUpdateRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_nomenclature_product_category_serialize(
            nomenclature_category_update_request=nomenclature_category_update_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def update_nomenclature_product_category_with_http_info(
        self,
        nomenclature_category_update_request: Annotated[NomenclatureCategoryUpdateRequest, Field(description="Request body for updating a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NomenclatureCategoryWriteResponse]:
        """Update a product category

        Updates an existing product category. Both `id` (UUID of the category to update) and `name` (new name) are required. 

        :param nomenclature_category_update_request: Request body for updating a product category (required)
        :type nomenclature_category_update_request: NomenclatureCategoryUpdateRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_nomenclature_product_category_serialize(
            nomenclature_category_update_request=nomenclature_category_update_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def update_nomenclature_product_category_without_preload_content(
        self,
        nomenclature_category_update_request: Annotated[NomenclatureCategoryUpdateRequest, Field(description="Request body for updating a product category")],
        timeout: Annotated[Optional[StrictInt], Field(description="Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update a product category

        Updates an existing product category. Both `id` (UUID of the category to update) and `name` (new name) are required. 

        :param nomenclature_category_update_request: Request body for updating a product category (required)
        :type nomenclature_category_update_request: NomenclatureCategoryUpdateRequest
        :param timeout: Default: <code>15</code></br> Example: <code>10</code></br> Timeout in seconds. 
        :type timeout: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_nomenclature_product_category_serialize(
            nomenclature_category_update_request=nomenclature_category_update_request,
            timeout=timeout,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NomenclatureCategoryWriteResponse",
            '400': "GenericErrorResponse",
            '401': "GenericErrorResponse",
            '403': "GenericErrorResponse",
            '429': "GenericErrorResponse",
            '500': "GenericErrorResponse",
            '502': "GenericErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_nomenclature_product_category_serialize(
        self,
        nomenclature_category_update_request,
        timeout,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if timeout is not None:
            _header_params['Timeout'] = timeout
        # process the form parameters
        # process the body parameter
        if nomenclature_category_update_request is not None:
            _body_params = nomenclature_category_update_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/nomenclature/v1/nomenclature/category/update',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


